      MODULE aval_I   
      INTERFACE
      DOUBLE PRECISION FUNCTION aval (H, D, NORBS) 
      integer, INTENT(IN) :: NORBS 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(IN) :: H 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(IN) :: D 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
