      MODULE bdenup_I   
      INTERFACE
      SUBROUTINE bdenup (BDCON, UAB, C, D, DA, NORBS, NCLOSE) 
      integer, INTENT(IN) :: NORBS 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(IN) :: BDCON 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(IN) :: UAB 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(IN) :: C 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(INOUT) :: D 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(INOUT) :: DA       
      integer, INTENT(IN) :: NCLOSE 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
