      MODULE bdenin_I   
      INTERFACE
      SUBROUTINE bdenin (BDCON, UA, UB, C, NORBS, NCLOSE) 
      integer, INTENT(IN) :: NORBS 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(OUT) :: BDCON 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(IN) :: UA 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(IN) :: UB 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(IN) :: C   
      integer, INTENT(IN) :: NCLOSE 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
