      MODULE betall_I   
      INTERFACE
      SUBROUTINE betall (U2A, G2A, U1B, G1B, U1C, G1C, NCLOSE, NORBS, TERM) 
      integer :: NCLOSE 
      integer, INTENT(IN) :: NORBS 
      DOUBLE PRECISION, INTENT(OUT) :: TERM 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS) :: U2A 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS) :: G2A 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS) :: U1B 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS) :: G1B 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS) :: U1C 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS) :: G1C 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
