      MODULE betcom_I   
      INTERFACE
      SUBROUTINE betcom (U1, G1, U2, G2, NCLOSE, NORBS, TERM) 
      integer :: NCLOSE 
      integer, INTENT(IN) :: NORBS 
      DOUBLE PRECISION, INTENT(OUT) :: TERM 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS) :: U1 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS) :: G1 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS) :: U2 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS) :: G2 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
