      MODULE capcor_I   
      INTERFACE
      DOUBLE PRECISION FUNCTION capcor (NAT, NFIRST, NLAST,  P, H) 
      use molkst_C, only : numat
      INTEGER, DIMENSION(NUMAT), INTENT(IN) :: NAT 
      INTEGER, DIMENSION(NUMAT), INTENT(IN) :: NFIRST 
      INTEGER, DIMENSION(NUMAT), INTENT(IN) :: NLAST  
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: P 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: H 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
