      MODULE charvi_I   
      INTERFACE
      DOUBLE PRECISION FUNCTION charvi (VECTS, JORB, IOPER, R, NVECS) 
      INTEGER, INTENT(IN) :: NVECS  
      DOUBLE PRECISION, DIMENSION(NVECS,NVECS), INTENT(IN) :: VECTS 
      INTEGER, INTENT(IN) :: JORB 
      INTEGER, INTENT(IN) :: IOPER 
      DOUBLE PRECISION, DIMENSION(3,3), INTENT(IN) :: R      
      END FUNCTION  
      END INTERFACE 
      END MODULE 
