      MODULE charmo_I   
      INTERFACE
      DOUBLE PRECISION FUNCTION charmo (VECTS, NTYPE, JORB, IOPER, R, NVECS, FIRST) 
      INTEGER, INTENT(IN) :: NVECS
      DOUBLE PRECISION, DIMENSION(NVECS,NVECS), INTENT(IN) :: VECTS 
      INTEGER, DIMENSION(*), INTENT(IN) :: NTYPE 
      INTEGER, INTENT(IN) :: JORB 
      INTEGER, INTENT(IN) :: IOPER 
      DOUBLE PRECISION, DIMENSION(3,3), INTENT(IN) :: R 
      LOGICAL, intent(inout) :: FIRST 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
