      MODULE chi_I   
      INTERFACE
      SUBROUTINE chi (TOLER, COORD, IOPER, IQUAL) 
      DOUBLE PRECISION, INTENT(IN) :: TOLER 
      DOUBLE PRECISION, DIMENSION(3,*), INTENT(IN) :: COORD 
      INTEGER, INTENT(IN) :: IOPER 
      INTEGER, INTENT(OUT) :: IQUAL 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
