      MODULE ciint_I   
      INTERFACE
      SUBROUTINE ciint (C34, PQ34) 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: C34 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: PQ34 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
