      MODULE cnvg_I   
      INTERFACE
      SUBROUTINE cnvg (PNEW, P, P1, NITER, PL) 
      DOUBLE PRECISION, DIMENSION(1234), INTENT(INOUT) :: PNEW 
      DOUBLE PRECISION, DIMENSION(1234), INTENT(INOUT) :: P 
      DOUBLE PRECISION, DIMENSION(1234), INTENT(INOUT) :: P1 
      INTEGER, INTENT(IN) :: NITER 
      DOUBLE PRECISION, INTENT(OUT) :: PL 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
