      MODULE coe_I   
      INTERFACE
      SUBROUTINE coe (X2, Y2, Z2, NORBI, NORBJ, C, R) 
      DOUBLE PRECISION, INTENT(IN) :: X2 
      DOUBLE PRECISION, INTENT(IN) :: Y2 
      DOUBLE PRECISION, INTENT(IN) :: Z2 
      INTEGER, INTENT(IN) :: NORBI 
      INTEGER, INTENT(IN) :: NORBJ 
      DOUBLE PRECISION, DIMENSION(75), INTENT(OUT) :: C 
      DOUBLE PRECISION, INTENT(OUT) :: R 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
