      MODULE collis_I   
      INTERFACE
      LOGICAL FUNCTION collis (CW, RW, CNBR, RNBR, NNBR, ISHAPE) 
      DOUBLE PRECISION, DIMENSION(3), INTENT(IN) :: CW 
      DOUBLE PRECISION, INTENT(IN) :: RW 
      DOUBLE PRECISION, DIMENSION(3,200), INTENT(IN) :: CNBR 
      DOUBLE PRECISION, DIMENSION(200), INTENT(IN) :: RNBR 
      integer, INTENT(IN) :: NNBR 
      integer, INTENT(IN) :: ISHAPE 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
