      MODULE compfn_I   
      INTERFACE
      SUBROUTINE compfn (XPARAM, INT, ESCF, FULSCF, GRAD, LGRAD, W, H, HQ, WJ&
        , WK) 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: XPARAM 
      LOGICAL, INTENT(IN) :: INT 
      DOUBLE PRECISION, INTENT(INOUT) :: ESCF 
      LOGICAL :: FULSCF 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: GRAD 
      LOGICAL, INTENT(IN) :: LGRAD 
      DOUBLE PRECISION, DIMENSION(*) :: W, H, HQ, WJ, WK
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
