      MODULE densf_I   
      INTERFACE
      SUBROUTINE densf (U, C, D, DA, NORBS, NCLOSE, W2) 
      integer, INTENT(IN) :: NORBS 
      integer, INTENT(IN) :: NCLOSE
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(IN) :: U 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(IN) :: C 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(OUT) :: D 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(OUT) :: DA 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(INOUT) :: W2 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
