      MODULE deri22_I   
      INTERFACE
      SUBROUTINE deri22 (C, B, WORK, FOC2, AB, MINEAR, FCI, W, DIAG&
        , SCALAR, NINEAR) 
      use molkst_C, only : norbs, n2elec 
      INTEGER, INTENT(IN) :: MINEAR, NINEAR
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS) :: C 
      DOUBLE PRECISION, DIMENSION(MINEAR), INTENT(INOUT) :: B 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(INOUT) :: WORK        
      DOUBLE PRECISION, DIMENSION(NORBS*NORBS), INTENT(OUT) :: FOC2 
      DOUBLE PRECISION, DIMENSION(MINEAR), INTENT(INOUT) :: AB       
      DOUBLE PRECISION, DIMENSION(NINEAR), INTENT(OUT) :: FCI 
      DOUBLE PRECISION, DIMENSION(n2elec) :: W 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: DIAG 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: SCALAR 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
