      MODULE deri0_I   
      INTERFACE
      SUBROUTINE deri0 (E, N, SCALAR, DIAG, FRACT, NBO) 
      INTEGER, INTENT(IN) :: N 
      DOUBLE PRECISION, DIMENSION(N), INTENT(IN) :: E       
      DOUBLE PRECISION, DIMENSION(*), INTENT(OUT) :: SCALAR 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: DIAG 
      DOUBLE PRECISION, INTENT(IN) :: FRACT 
      INTEGER, DIMENSION(3), INTENT(IN) :: NBO 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
