      MODULE deri21_I   
      INTERFACE
      SUBROUTINE deri21 (A, NVAR, MINEAR, NFIRST, VNERT, PNERT, B, NCUT) 
      INTEGER, INTENT(IN) :: NVAR 
      INTEGER, INTENT(IN) :: MINEAR 
      INTEGER, INTENT(IN) :: NFIRST 
      DOUBLE PRECISION, DIMENSION(MINEAR,NVAR) :: A 
      DOUBLE PRECISION, DIMENSION(NVAR), INTENT(INOUT) :: VNERT 
      DOUBLE PRECISION, DIMENSION(NVAR), INTENT(INOUT) :: PNERT 
      DOUBLE PRECISION, DIMENSION(MINEAR,*) :: B 
      INTEGER, INTENT(OUT) :: NCUT 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
