      MODULE dfock2_I   
      INTERFACE
      SUBROUTINE dfock2 (F, PTOT, P, W, NUMAT, NFIRST, NLAST, NATI) 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: F 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: PTOT 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: P 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: W 
      INTEGER, INTENT(IN) :: NUMAT 
      INTEGER, DIMENSION(*), INTENT(IN) :: NFIRST 
      INTEGER, DIMENSION(*), INTENT(IN) :: NLAST 
      INTEGER, INTENT(IN) :: NATI 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
