      MODULE dfpsav_I   
      INTERFACE
      SUBROUTINE dfpsav (TOTIME, XPARAM, GD, XLAST, FUNCT1, MDFP, XDFP) 
      DOUBLE PRECISION, INTENT(IN) :: TOTIME 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: XPARAM 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: GD 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: XLAST 
      DOUBLE PRECISION, INTENT(IN) :: FUNCT1 
      INTEGER, DIMENSION(9), INTENT(IN) :: MDFP 
      DOUBLE PRECISION, DIMENSION(9), INTENT(IN) :: XDFP 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
