      MODULE dgetri_I   
      INTERFACE
      SUBROUTINE dgetri (N, A, LDA, IPIV, WORK, LWORK) 
      integer, INTENT(IN) :: N, LDA, LWORK
      DOUBLE PRECISION, DIMENSION(LDA,*), INTENT(INOUT) :: A  
      integer, DIMENSION(*), INTENT(IN) :: IPIV 
      DOUBLE PRECISION, DIMENSION(LWORK), INTENT(OUT) :: WORK 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
