      MODULE dhc_I   
      INTERFACE
      SUBROUTINE dhc (P, PA, PB, XI, NAT, IF, IL, JF, JL, DENER, MODE) 
      DOUBLE PRECISION, DIMENSION(171), intent(in) :: P, pa, pb
      DOUBLE PRECISION, DIMENSION(3,2), INTENT(IN) :: XI 
      INTEGER, DIMENSION(2), INTENT(IN) :: NAT 
      INTEGER, INTENT(IN) :: IF 
      INTEGER, INTENT(IN) :: IL 
      INTEGER, INTENT(IN) :: JF 
      INTEGER, INTENT(IN) :: JL 
      DOUBLE PRECISION, INTENT(OUT) :: DENER 
      INTEGER, INTENT(IN) :: MODE 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
