      MODULE diag_I   
      INTERFACE
      SUBROUTINE diag (FAO, VECTOR, NOCC, EIG, MDIM, N) 
      INTEGER, INTENT(IN) :: MDIM 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: FAO 
      DOUBLE PRECISION, DIMENSION(MDIM,MDIM), INTENT(INOUT) :: VECTOR 
      INTEGER, INTENT(IN) :: NOCC 
      DOUBLE PRECISION, DIMENSION(MDIM), INTENT(IN) :: EIG 
      INTEGER, INTENT(IN) :: N 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
