      MODULE diagi_I   
      INTERFACE
      DOUBLE PRECISION FUNCTION diagi (IALPHA, IBETA, EIGA, XY, NMOS) 
      use meci_C, only : nmeci 
      INTEGER, INTENT(IN) :: NMOS 
      INTEGER, DIMENSION(NMOS), INTENT(IN) :: IALPHA 
      INTEGER, DIMENSION(NMOS), INTENT(IN) :: IBETA 
      DOUBLE PRECISION, DIMENSION(NMECI), INTENT(IN) :: EIGA 
      DOUBLE PRECISION, DIMENSION(NMOS,NMOS,NMOS,NMOS), INTENT(IN) :: XY       
      END FUNCTION  
      END INTERFACE 
      END MODULE 
