      MODULE diat2_I   
      INTERFACE
      SUBROUTINE diat2 (NA, ESA, EPA, R12, NB, ESB, EPB, S, A0) 
      INTEGER, INTENT(IN) :: NA 
      DOUBLE PRECISION :: ESA 
      DOUBLE PRECISION :: EPA 
      DOUBLE PRECISION, INTENT(IN) :: R12 
      INTEGER, INTENT(IN) :: NB 
      DOUBLE PRECISION :: ESB 
      DOUBLE PRECISION :: EPB 
      DOUBLE PRECISION, DIMENSION(3,3,3), INTENT(INOUT) :: S 
      DOUBLE PRECISION, INTENT(IN) :: A0 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
