      MODULE diat_I   
      INTERFACE
      SUBROUTINE diat (NI, NJ, XJ, DI) 
      INTEGER, INTENT(IN) :: NI 
      INTEGER, INTENT(IN) :: NJ 
      DOUBLE PRECISION, DIMENSION(3), INTENT(IN) :: XJ 
      DOUBLE PRECISION, DIMENSION(9,9), INTENT(OUT) :: DI 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
