      MODULE dijkl1_I   
      INTERFACE
      SUBROUTINE dijkl1 (C, N, NATI, W, CIJ, WCIJ, CKL, XY) 
      use meci_C, only : nmos    
      INTEGER, INTENT(IN) :: N 
      INTEGER, INTENT(IN) :: NATI 
      DOUBLE PRECISION, DIMENSION(N,*), INTENT(IN) :: C 
      DOUBLE PRECISION, DIMENSION(*) :: W 
      DOUBLE PRECISION, DIMENSION(*), INTENT(OUT) :: CIJ 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: WCIJ 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: CKL 
      DOUBLE PRECISION, DIMENSION(NMOS,NMOS,NMOS,NMOS), INTENT(OUT) :: XY 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
