      MODULE dijkld_I   
      INTERFACE
      SUBROUTINE dijkld (C, N, NATI, W, WD, CIJ, WCIJ, CKL, XY) 
      integer, INTENT(IN) :: N 
      integer, INTENT(IN) :: NATI 
      DOUBLE PRECISION, DIMENSION(N,*), INTENT(IN) :: C 
      DOUBLE PRECISION, DIMENSION(*) :: W 
      DOUBLE PRECISION, DIMENSION(*) :: WD 
      DOUBLE PRECISION, DIMENSION(*), INTENT(OUT) :: CIJ 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: WCIJ 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: CKL 
      DOUBLE PRECISION, DIMENSION(*), INTENT(OUT) :: XY 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
