      MODULE dipole_I   
      INTERFACE
      DOUBLE PRECISION FUNCTION dipole (P, COORD, DIPVEC, MODE) 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: P 
      DOUBLE PRECISION, DIMENSION(3,*), INTENT(INOUT) :: COORD 
      DOUBLE PRECISION, DIMENSION(3), INTENT(OUT) :: DIPVEC 
      INTEGER, INTENT(IN) :: MODE 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
