      MODULE dofs_I   
      INTERFACE
      SUBROUTINE dofs (EREF, MONO3, N, DD, M, BOTTOM, TOP) 
      INTEGER, INTENT(IN) :: MONO3 
      INTEGER, INTENT(IN) :: N       
      INTEGER, INTENT(IN) :: M 
      DOUBLE PRECISION, DIMENSION(MONO3,N), INTENT(INOUT) :: EREF 
      DOUBLE PRECISION, DIMENSION(M), INTENT(INOUT) :: DD 
      DOUBLE PRECISION, INTENT(IN) :: BOTTOM 
      DOUBLE PRECISION, INTENT(IN) :: TOP 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
