      MODULE dot_I   
      INTERFACE
      DOUBLE PRECISION FUNCTION dot (X, Y, N) 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: X 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: Y 
      INTEGER, INTENT(IN) :: N 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
