      MODULE drepp2_I   
      INTERFACE
      SUBROUTINE drepp2 (NI, RIJ, RI, CORE) 
      integer, INTENT(IN) :: NI 
      DOUBLE PRECISION, INTENT(IN) :: RIJ 
      DOUBLE PRECISION, DIMENSION(22), INTENT(OUT) :: RI 
      DOUBLE PRECISION, DIMENSION(4,2), INTENT(OUT) :: CORE 

      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
