      MODULE elau_I   
      INTERFACE
      SUBROUTINE elau (HINV, L, D, A, E) 
      DOUBLE PRECISION, INTENT(IN) :: HINV 
      integer, INTENT(IN) :: L 
      DOUBLE PRECISION, DIMENSION(L), INTENT(IN) :: D 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: A 
      DOUBLE PRECISION, DIMENSION(L), INTENT(INOUT) :: E 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
