      MODULE esn_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:13  03/09/06  
      SUBROUTINE esn ( AL, A, ESPI, OVL, CESPM2, CESPML, CESP, POTPT, ES&
        , ESPC, WORK1D, NORBS, NUMAT) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: NORBS 
      integer, INTENT(IN) :: NUMAT 
      real(DOUBLE), DIMENSION((NUMAT + 1)**2) :: AL 
      real(DOUBLE), DIMENSION(NORBS**2) :: CESPM2 
      real(DOUBLE), DIMENSION(NORBS**2) :: CESPML 
      real(DOUBLE), DIMENSION(NORBS**2) :: CESP 
      real(DOUBLE), DIMENSION(3,*) :: POTPT 
      real(DOUBLE), DIMENSION(*) :: ES 
      real(DOUBLE), DIMENSION(*) :: ESPC 
      real(DOUBLE), DIMENSION(*) :: WORK1D     
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
