      MODULE exchng_I   
      INTERFACE
      SUBROUTINE exchng (A, B, C, D, X, Y, T, Q, N) 
      DOUBLE PRECISION, INTENT(IN) :: A 
      DOUBLE PRECISION, INTENT(OUT) :: B 
      DOUBLE PRECISION, INTENT(IN) :: C 
      DOUBLE PRECISION, INTENT(OUT) :: D 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: X 
      DOUBLE PRECISION, DIMENSION(*), INTENT(OUT) :: Y 
      DOUBLE PRECISION, INTENT(IN) :: T 
      DOUBLE PRECISION, INTENT(OUT) :: Q 
      INTEGER, INTENT(IN) :: N 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
