      MODULE ffreq1_I   
      INTERFACE
      SUBROUTINE ffreq1 (F, PTOT, PA, PB, NDIM) 
      integer, INTENT(IN) :: NDIM 
      DOUBLE PRECISION, DIMENSION(NDIM,NDIM), INTENT(INOUT) :: F 
      DOUBLE PRECISION, DIMENSION(NDIM,NDIM), INTENT(IN) :: PTOT 
      DOUBLE PRECISION, DIMENSION(NDIM,NDIM), INTENT(IN) :: PA 
      DOUBLE PRECISION, DIMENSION(NDIM,NDIM), INTENT(IN) :: PB       
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
