      MODULE flepo_I   
      INTERFACE
      SUBROUTINE flepo (XPARAM, NVAR, FUNCT1) 
      INTEGER, INTENT(IN) :: NVAR
      DOUBLE PRECISION, DIMENSION(NVAR) :: XPARAM        
      DOUBLE PRECISION :: FUNCT1 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
