      MODULE fock2_I   
      INTERFACE
      SUBROUTINE fock2 (F, PTOT, P, W, WJ, WK, NUMAT, NFIRST, NLAST, MODE) 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: F 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: PTOT 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: P 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: W 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: WJ 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: WK 
      INTEGER, INTENT(IN) :: NUMAT, MODE
      INTEGER, DIMENSION(*), INTENT(IN) :: NFIRST 
      INTEGER, DIMENSION(*), INTENT(IN) :: NLAST 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
