      MODULE fockd2_I   
      INTERFACE
      SUBROUTINE fockd2 (F, PTOT, P, W, LMW, WJ, WK, NUMAT, NFIRST, NLAST, NW) 
      integer, INTENT(IN) :: LMW, NUMAT 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: F 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: PTOT 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: P 
      DOUBLE PRECISION, DIMENSION(LMW,LMW), INTENT(IN) :: W       
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: WJ 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: WK 
      integer, DIMENSION(NUMAT), INTENT(IN) :: NFIRST 
      integer, DIMENSION(NUMAT), INTENT(IN) :: NLAST 
      integer, DIMENSION(NUMAT), INTENT(IN) :: NW 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
