      MODULE formxy_I   
      INTERFACE
      SUBROUTINE formxy (W, KR, WCA, WCB, CA, NA, CB, NB) 
      DOUBLE PRECISION, DIMENSION(100), INTENT(IN) :: W 
      INTEGER, INTENT(INOUT) :: KR
      INTEGER, INTENT(IN) :: NA, NB 
      DOUBLE PRECISION, DIMENSION(NA), INTENT(INOUT) :: WCA 
      DOUBLE PRECISION, DIMENSION(NB), INTENT(INOUT) :: WCB 
      DOUBLE PRECISION, DIMENSION(NA), INTENT(IN) :: CA        
      DOUBLE PRECISION, DIMENSION(NB), INTENT(IN) :: CB 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
