      MODULE frame_I   
      INTERFACE
      SUBROUTINE frame (FMAT, NUMAT, MODE) 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: FMAT 
      INTEGER, INTENT(IN) :: NUMAT 
      INTEGER, INTENT(IN) :: MODE 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
