      MODULE gstore_I   
      INTERFACE
      SUBROUTINE gstore (II, JJ, KK, LL, WERT, PGR) 
      INTEGER, INTENT(IN) :: II 
      INTEGER, INTENT(IN) :: JJ 
      INTEGER, INTENT(IN) :: KK 
      INTEGER, INTENT(IN) :: LL 
      DOUBLE PRECISION, INTENT(IN) :: WERT 
      DOUBLE PRECISION, DIMENSION(*), INTENT(OUT) :: PGR 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
