      MODULE h1elec_I   
      INTERFACE
      SUBROUTINE h1elec (NI, NJ, XI, XJ, SMAT) 
      INTEGER, INTENT(IN) :: NI 
      INTEGER, INTENT(IN) :: NJ 
      DOUBLE PRECISION, DIMENSION(3), INTENT(IN) :: XI 
      DOUBLE PRECISION, DIMENSION(3), INTENT(IN) :: XJ 
      DOUBLE PRECISION, DIMENSION(9,9), INTENT(OUT) :: SMAT 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
