      MODULE helect_I   
      INTERFACE
      DOUBLE PRECISION FUNCTION helect (N, P, H, F) 
      INTEGER, INTENT(IN) :: N 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: P 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: H 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: F 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
