      MODULE intfc_I   
      INTERFACE
      SUBROUTINE intfc (FMATRX, XPARAM, GEOREF, NAR, NBR, NCR) 
      use molkst_C, only : nvar, natoms
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: FMATRX 
      DOUBLE PRECISION, DIMENSION(NVAR), INTENT(OUT) :: XPARAM 
      DOUBLE PRECISION, DIMENSION(3,NATOMS), INTENT(IN) :: GEOREF 
      INTEGER, DIMENSION(NATOMS), INTENT(IN) :: NAR 
      INTEGER, DIMENSION(NATOMS), INTENT(IN) :: NBR 
      INTEGER, DIMENSION(NATOMS), INTENT(IN) :: NCR 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
