      MODULE jab_I   
      INTERFACE
      SUBROUTINE jab (IA, JA, PJA, PJB, W, F) 
      INTEGER, INTENT(IN) :: IA 
      INTEGER, INTENT(IN) :: JA 
      DOUBLE PRECISION, DIMENSION(16), INTENT(IN) :: PJA 
      DOUBLE PRECISION, DIMENSION(16), INTENT(IN) :: PJB 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: W 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: F 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
