      MODULE makopr_I   
      INTERFACE
      SUBROUTINE makopr (NUMAT, COORD, IERROR, R) 
      INTEGER :: NUMAT 
      DOUBLE PRECISION, DIMENSION(*) :: COORD 
      INTEGER, INTENT(OUT) :: IERROR 
      DOUBLE PRECISION, DIMENSION(3,3) :: R 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
