      MODULE mamult_I   
      INTERFACE
      SUBROUTINE mamult (A, B, C, N, ONE) 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: A 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: B 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: C 
      INTEGER, INTENT(IN) :: N 
      DOUBLE PRECISION, INTENT(IN) :: ONE 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
