      MODULE molsym_I   
      INTERFACE
      SUBROUTINE molsym (COORD, IERROR, R) 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: COORD 
      INTEGER, INTENT(OUT) :: IERROR 
      DOUBLE PRECISION, DIMENSION(3,3), INTENT(OUT) :: R 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
