      MODULE mtxmc_I   
      INTERFACE
      SUBROUTINE mtxmc (A, NAR, B, NBR, C) 
      INTEGER, INTENT(IN) :: NAR, NBR
      DOUBLE PRECISION, DIMENSION(NBR,NAR) :: A       
      DOUBLE PRECISION, DIMENSION(NBR,NAR) :: B 
      DOUBLE PRECISION, DIMENSION(*) :: C 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
