      MODULE mxmt_I   
      INTERFACE
      SUBROUTINE mxmt (A, NAR, B, NBR, C, NCC) 
      INTEGER, INTENT(IN) :: NAR, NBR, NCC
      DOUBLE PRECISION, DIMENSION(NAR,NBR) :: A       
      DOUBLE PRECISION, DIMENSION(NCC,NBR) :: B 
      DOUBLE PRECISION, DIMENSION(NAR,NCC) :: C 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
