      MODULE osinv_I   
      INTERFACE
      SUBROUTINE osinv (A, N, D) 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: A 
      INTEGER, INTENT(IN) :: N 
      DOUBLE PRECISION, INTENT(OUT) :: D 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
