      MODULE plato_I   
      INTERFACE
      SUBROUTINE plato (COORD, R, CUBIC) 
      LOGICAL, INTENT(OUT) :: CUBIC
      DOUBLE PRECISION, DIMENSION(3,*), INTENT(IN) :: COORD        
      DOUBLE PRECISION, DIMENSION(3,3), INTENT(INOUT) :: R 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
