      MODULE prttim_I   
      INTERFACE
      SUBROUTINE prttim (TLEFT, TPRT, TXT) 
      DOUBLE PRECISION, INTENT(IN) :: TLEFT 
      DOUBLE PRECISION, INTENT(OUT) :: TPRT 
      CHARACTER (LEN = 1), INTENT(OUT) :: TXT 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
