      MODULE pulay_I   
      INTERFACE
      SUBROUTINE pulay (F, P, N, FPPF, FOCK, EMAT, LFOCK, NFOCK, MSIZE, START&
        , PL) 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: F 
      DOUBLE PRECISION, DIMENSION(*) :: P 
      INTEGER, INTENT(IN) :: N 
      DOUBLE PRECISION, DIMENSION(*) :: FPPF 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: FOCK 
      DOUBLE PRECISION, DIMENSION(20,20), INTENT(INOUT) :: EMAT 
      INTEGER, INTENT(INOUT) :: LFOCK 
      INTEGER, INTENT(INOUT) :: NFOCK 
      INTEGER, INTENT(IN) :: MSIZE 
      LOGICAL, INTENT(INOUT) :: START 
      DOUBLE PRECISION, INTENT(OUT) :: PL 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
