      MODULE quadr_I   
      INTERFACE
      SUBROUTINE quadr (F0, F1, F2, X1, X2, A, B, C) 
      DOUBLE PRECISION, INTENT(IN) :: F0 
      DOUBLE PRECISION, INTENT(IN) :: F1 
      DOUBLE PRECISION, INTENT(IN) :: F2 
      DOUBLE PRECISION, INTENT(IN) :: X1 
      DOUBLE PRECISION, INTENT(IN) :: X2 
      DOUBLE PRECISION, INTENT(OUT) :: A 
      DOUBLE PRECISION, INTENT(OUT) :: B 
      DOUBLE PRECISION, INTENT(OUT) :: C 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
