      MODULE reppd2_I   
      INTERFACE
      SUBROUTINE reppd2 (NI, NJ, R, RI, REP, CORE) 
      integer, INTENT(IN) :: NI 
      integer, INTENT(IN) :: NJ 
      DOUBLE PRECISION :: R 
      DOUBLE PRECISION, DIMENSION(22), INTENT(IN) :: RI 
      DOUBLE PRECISION, DIMENSION(491), INTENT(OUT) :: REP 
      DOUBLE PRECISION, DIMENSION(10,2), INTENT(OUT) :: CORE 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
