      MODULE resolv_I   
      INTERFACE
      SUBROUTINE resolv (C, COLD, MDIM, EIG, NOCC) 
      INTEGER, INTENT(IN) :: MDIM, NOCC
      DOUBLE PRECISION, DIMENSION(MDIM,MDIM), INTENT(INOUT) :: C 
      DOUBLE PRECISION, DIMENSION(MDIM,MDIM), INTENT(IN) :: COLD      
      DOUBLE PRECISION, DIMENSION(NOCC), INTENT(IN) :: EIG 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
