      MODULE rotate_I   
      INTERFACE
      SUBROUTINE rotate (NI, NJ, XI, XJ, W, KR, E1B, E2A, ENUC) 
      INTEGER, INTENT(IN) :: NI 
      INTEGER, INTENT(IN) :: NJ 
      DOUBLE PRECISION, DIMENSION(3), INTENT(IN) :: XI 
      DOUBLE PRECISION, DIMENSION(3), INTENT(IN) :: XJ 
      DOUBLE PRECISION, DIMENSION(*), INTENT(OUT) :: W 
      INTEGER, INTENT(INOUT) :: KR 
      DOUBLE PRECISION, DIMENSION(45), INTENT(OUT) :: E1B 
      DOUBLE PRECISION, DIMENSION(45), INTENT(OUT) :: E2A 
      DOUBLE PRECISION, INTENT(OUT) :: ENUC 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
