      MODULE rotmol_I   
      INTERFACE
      SUBROUTINE rotmol (NUMAT, COORD, SINA, COSA, I, J, R) 
      INTEGER :: NUMAT 
      DOUBLE PRECISION, DIMENSION(3,NUMAT) :: COORD 
      DOUBLE PRECISION, INTENT(IN) :: SINA 
      DOUBLE PRECISION, INTENT(IN) :: COSA 
      INTEGER, INTENT(IN) :: I 
      INTEGER, INTENT(IN) :: J 
      DOUBLE PRECISION, DIMENSION(3,3), INTENT(INOUT) :: R 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
