      MODULE set_I   
      INTERFACE
      SUBROUTINE set (S1, S2, NA, NB, RAB, II) 
      DOUBLE PRECISION, INTENT(IN) :: S1 
      DOUBLE PRECISION, INTENT(IN) :: S2 
      INTEGER, INTENT(IN) :: NA 
      INTEGER, INTENT(IN) :: NB 
      DOUBLE PRECISION, INTENT(IN) :: RAB 
      INTEGER, INTENT(IN) :: II 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
