      MODULE solrot_I   
      INTERFACE
      SUBROUTINE solrot (NI, NJ, XI, XJ, WJ, WK, KR, E1B, E2A, ENUC) 
      INTEGER, INTENT(IN) :: NI 
      INTEGER, INTENT(IN) :: NJ 
      DOUBLE PRECISION, DIMENSION(3), INTENT(IN) :: XI 
      DOUBLE PRECISION, DIMENSION(3), INTENT(IN) :: XJ 
      DOUBLE PRECISION, DIMENSION(2025), INTENT(OUT) :: WJ, wk
      INTEGER, INTENT(INOUT) :: KR 
      DOUBLE PRECISION, DIMENSION(45), INTENT(INOUT) :: E1B 
      DOUBLE PRECISION, DIMENSION(45), INTENT(INOUT) :: E2A 
      DOUBLE PRECISION, INTENT(OUT) :: ENUC 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
