      MODULE supdot_I   
      INTERFACE
      SUBROUTINE supdot (S, H, G, N) 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: S 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: H 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: G 
      INTEGER, INTENT(IN) :: N 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
