      MODULE superd_I   
      INTERFACE
      SUBROUTINE superd (C, EIGS, NORBS, NELECS, NUMAT, NAT) 
      INTEGER, INTENT(IN) :: NORBS 
      INTEGER, INTENT(IN) :: NELECS 
      INTEGER, INTENT(IN) :: NUMAT
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(IN) :: C 
      DOUBLE PRECISION, DIMENSION(NORBS), INTENT(IN) :: EIGS        
      INTEGER, DIMENSION(NUMAT), INTENT(IN) :: NAT 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
