      MODULE swap_I   
      INTERFACE
      SUBROUTINE swap (C, N, MDIM, NOCC, IFILL) 
      INTEGER, INTENT(IN) :: N 
      INTEGER, INTENT(IN) :: MDIM 
      INTEGER, INTENT(IN) :: NOCC 
      INTEGER, INTENT(INOUT) :: IFILL
      DOUBLE PRECISION, DIMENSION(MDIM,MDIM), INTENT(INOUT) :: C 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
