      MODULE symopr_I   
      INTERFACE
      SUBROUTINE symopr (NUMAT, COORD, JUMP, R) 
      INTEGER, INTENT(IN) :: NUMAT 
      DOUBLE PRECISION, DIMENSION(3,NUMAT), INTENT(INOUT) :: COORD 
      INTEGER, INTENT(IN) :: JUMP 
      DOUBLE PRECISION, DIMENSION(3,3), INTENT(IN) :: R 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
