      MODULE sympop_I   
      INTERFACE
      SUBROUTINE sympop (H, I, ISKIP, DELDIP) 
      DOUBLE PRECISION, DIMENSION(*) :: H 
      INTEGER, INTENT(IN) :: I 
      INTEGER, INTENT(OUT) :: ISKIP 
      DOUBLE PRECISION, DIMENSION(3,*) :: DELDIP 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
