      MODULE symt_I   
      INTERFACE
      SUBROUTINE symt (H, DELDIP, HA) 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: H 
      DOUBLE PRECISION, DIMENSION(3,*), INTENT(INOUT) :: DELDIP 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: HA 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
