      MODULE tf_I   
      INTERFACE
      SUBROUTINE tf (UA, GA, UB, GB, T, NORBS) 
      integer, INTENT(IN) :: NORBS 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(IN) :: UA 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(IN) :: GA 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(IN) :: UB 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(IN) :: GB 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(OUT) :: T    
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
