      MODULE transf_I   
      INTERFACE
      SUBROUTINE transf (F, G, C, NORB) 
      integer, INTENT(IN) :: NORB 
      DOUBLE PRECISION, DIMENSION(NORB,NORB), INTENT(IN) :: F 
      DOUBLE PRECISION, DIMENSION(NORB,NORB), INTENT(OUT) :: G 
      DOUBLE PRECISION, DIMENSION(NORB,NORB), INTENT(IN) :: C       
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
