      MODULE xyzcry_I   
      INTERFACE
      SUBROUTINE xyzcry (TVEC, NUMAT, DXYZ, IW) 
      DOUBLE PRECISION, DIMENSION(3,3), INTENT(INOUT) :: TVEC 
      INTEGER, INTENT(IN) :: NUMAT 
      DOUBLE PRECISION, DIMENSION(3,*), INTENT(INOUT) :: DXYZ 
      INTEGER, INTENT(IN) :: IW 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
