      MODULE xyzint_I   
      INTERFACE
      SUBROUTINE xyzint (XYZ, numat, NA, NB, NC, DEGREE, GEO) 
!GBR
      integer :: numat      
      DOUBLE PRECISION, DIMENSION(3,NUMAT), INTENT(IN) :: XYZ  
      INTEGER, DIMENSION(NUMAT), INTENT(INOUT) :: NA 
      INTEGER, DIMENSION(NUMAT), INTENT(INOUT) :: NB 
      INTEGER, DIMENSION(NUMAT), INTENT(OUT) :: NC 
      DOUBLE PRECISION :: DEGREE 
      DOUBLE PRECISION, DIMENSION(3,NUMAT), INTENT(OUT) :: GEO 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
