      MODULE ccprod_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:18  03/09/06  
      SUBROUTINE ccprod (C1, C2, C12, LM2) 
      USE vast_kind_param,ONLY: DOUBLE
      integer, INTENT(IN) :: LM2  
      real(DOUBLE), DIMENSION(LM2), INTENT(IN) :: C1 
      real(DOUBLE), DIMENSION(LM2), INTENT(IN) :: C2 
      real(DOUBLE), DIMENSION(*), INTENT(OUT) :: C12 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
