      MODULE dgemv_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  22:48:56  03/08/06  
      SUBROUTINE dgemv (TRANS, M, N, ALPHA, A, LDA, X, INCX, BETA, Y, INCY) 
      USE vast_kind_param,ONLY: DOUBLE 
      character (LEN = *) :: TRANS 
      integer, INTENT(IN) :: M 
      integer, INTENT(IN) :: N, LDA, INCX, INCY
      real(DOUBLE), INTENT(IN) :: ALPHA 
      real(DOUBLE), DIMENSION(LDA,*), INTENT(IN) :: A  
      real(DOUBLE), DIMENSION(*), INTENT(IN) :: X  
      real(DOUBLE), INTENT(IN) :: BETA 
      real(DOUBLE), DIMENSION(*), INTENT(INOUT) :: Y 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
