      MODULE dimens_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:09  03/09/06  
      SUBROUTINE dimens (COORD, IW) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(3,*), INTENT(INOUT) :: COORD 
      INTEGER, INTENT(IN) :: IW 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
