      MODULE addhcr_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  14:15:03  03/10/06  
      SUBROUTINE addhcr () 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
