      MODULE aval_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  21:23:38  03/14/06  
      REAL(KIND(0.0D0)) FUNCTION aval (H, D, NORBS) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: NORBS 
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(IN) :: H 
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(IN) :: D 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
