      MODULE axis_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:00  03/09/06  
      SUBROUTINE axis (A, B, C, EVEC) 
      USE vast_kind_param,ONLY: DOUBLE
      REAL(DOUBLE), INTENT(OUT) :: A 
      REAL(DOUBLE), INTENT(OUT) :: B 
      REAL(DOUBLE), INTENT(OUT) :: C 
      REAL(DOUBLE), DIMENSION(3,3), INTENT(OUT) :: EVEC
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
