      MODULE axis_I   
      INTERFACE
      SUBROUTINE axis (A, B, C, EVEC) 
      DOUBLE PRECISION, INTENT(OUT) :: A 
      DOUBLE PRECISION, INTENT(OUT) :: B 
      DOUBLE PRECISION, INTENT(OUT) :: C 
      DOUBLE PRECISION, DIMENSION(3,3), INTENT(OUT) :: EVEC
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
