      MODULE babbcd_I   
      INTERFACE
      DOUBLE PRECISION FUNCTION babbcd (IOCCA1, IOCCB1, IOCCA2, IOCCB2, NMOS&
        , XY) 
      INTEGER, INTENT(IN) :: NMOS 
      INTEGER, DIMENSION(NMOS), INTENT(IN) :: IOCCA1 
      INTEGER, DIMENSION(NMOS), INTENT(IN) :: IOCCB1 
      INTEGER, DIMENSION(NMOS), INTENT(IN) :: IOCCA2 
      INTEGER, DIMENSION(NMOS), INTENT(IN) :: IOCCB2       
      DOUBLE PRECISION, DIMENSION(NMOS,NMOS,NMOS,NMOS), INTENT(IN) :: XY 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
