      MODULE bangle_I   
      INTERFACE
      SUBROUTINE bangle (XYZ, I, J, K, ANGLE) 
      DOUBLE PRECISION, DIMENSION(3,*), INTENT(IN) :: XYZ 
      INTEGER, INTENT(IN) :: I 
      INTEGER, INTENT(IN) :: J 
      INTEGER, INTENT(IN) :: K 
      DOUBLE PRECISION, INTENT(OUT) :: ANGLE 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
