      MODULE bangle_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  08:33:12  03/09/06  
      SUBROUTINE bangle (XYZ, I, J, K, ANGLE) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(3,*), INTENT(IN) :: XYZ 
      INTEGER, INTENT(IN) :: I 
      INTEGER, INTENT(IN) :: J 
      INTEGER, INTENT(IN) :: K 
      REAL(DOUBLE), INTENT(OUT) :: ANGLE 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
