      MODULE bdenup_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  21:23:38  03/14/06  
      SUBROUTINE bdenup (BDCON, UAB, C, D, DA, NORBS, NCLOSE) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: NORBS 
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(IN) :: BDCON 
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(IN) :: UAB 
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(IN) :: C 
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(INOUT) :: D 
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(INOUT) :: DA       
      integer, INTENT(IN) :: NCLOSE 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
