      MODULE bdenin_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  21:23:38  03/14/06  
      SUBROUTINE bdenin (BDCON, UA, UB, C, NORBS, NCLOSE) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: NORBS 
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(OUT) :: BDCON 
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(IN) :: UA 
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(IN) :: UB 
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(IN) :: C   
      integer, INTENT(IN) :: NCLOSE 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
