      MODULE beopor_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  21:23:38  03/14/06  
      SUBROUTINE beopor (IWFLB, MAXITU, BTOL, UA, UB, F, GA, GB, T, H1, D, DA&
        , UAB, UOLD1, G, X, C, W) 
      USE vast_kind_param,ONLY: DOUBLE 
      use molkst_C, only : norbs
      integer, INTENT(IN) :: IWFLB 
      integer, INTENT(IN) :: MAXITU 
      real(DOUBLE) :: BTOL 
      real(DOUBLE), DIMENSION(norbs,norbs) :: UA 
      real(DOUBLE), DIMENSION(norbs,norbs) :: UB 
      real(DOUBLE), DIMENSION(norbs,norbs) :: F 
      real(DOUBLE), DIMENSION(norbs,norbs) :: GA 
      real(DOUBLE), DIMENSION(norbs,norbs) :: GB 
      real(DOUBLE), DIMENSION(norbs,norbs) :: T 
      real(DOUBLE), DIMENSION(norbs,norbs) :: H1 
      real(DOUBLE), DIMENSION(norbs,norbs) :: D 
      real(DOUBLE), DIMENSION(norbs,norbs) :: DA 
      real(DOUBLE), DIMENSION(norbs,norbs) :: UAB 
      real(DOUBLE), DIMENSION(norbs,norbs) :: UOLD1 
      real(DOUBLE), DIMENSION(norbs,norbs) :: G 
      real(DOUBLE), DIMENSION(norbs,norbs) :: X 
      real(DOUBLE), DIMENSION(*), intent(in) :: C 
      real(DOUBLE), DIMENSION(*) :: W 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
