      MODULE betal1_I   
      INTERFACE
      SUBROUTINE betal1 (U0A, G0A, U1B, G1B, U1C, G1C, NCLOSE, NORBS, TERM) 
      integer :: NCLOSE 
      integer, INTENT(IN) :: NORBS 
      DOUBLE PRECISION, INTENT(OUT) :: TERM 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS) :: U0A 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS) :: G0A 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS) :: U1B 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS) :: G1B 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS) :: U1C 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS) :: G1C 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
