      MODULE betal1_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  21:23:38  03/14/06  
      SUBROUTINE betal1 (U0A, G0A, U1B, G1B, U1C, G1C, NCLOSE, NORBS, TERM) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer :: NCLOSE 
      integer, INTENT(IN) :: NORBS 
      real(DOUBLE), INTENT(OUT) :: TERM 
      real(DOUBLE), DIMENSION(NORBS,NORBS) :: U0A 
      real(DOUBLE), DIMENSION(NORBS,NORBS) :: G0A 
      real(DOUBLE), DIMENSION(NORBS,NORBS) :: U1B 
      real(DOUBLE), DIMENSION(NORBS,NORBS) :: G1B 
      real(DOUBLE), DIMENSION(NORBS,NORBS) :: U1C 
      real(DOUBLE), DIMENSION(NORBS,NORBS) :: G1C 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
