      MODULE betcom_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  21:23:38  03/14/06  
      SUBROUTINE betcom (U1, G1, U2, G2, NCLOSE, NORBS, TERM) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer :: NCLOSE 
      integer, INTENT(IN) :: NORBS 
      real(DOUBLE), INTENT(OUT) :: TERM 
      real(DOUBLE), DIMENSION(NORBS,NORBS) :: U1 
      real(DOUBLE), DIMENSION(NORBS,NORBS) :: G1 
      real(DOUBLE), DIMENSION(NORBS,NORBS) :: U2 
      real(DOUBLE), DIMENSION(NORBS,NORBS) :: G2 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
