      MODULE bfn_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:01  03/09/06  
      SUBROUTINE bfn (X, BF) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), INTENT(IN) :: X 
      REAL(DOUBLE), DIMENSION(13), INTENT(OUT) :: BF 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
