      MODULE bfn_I   
      INTERFACE
      SUBROUTINE bfn (X, BF) 
      DOUBLE PRECISION, INTENT(IN) :: X 
      DOUBLE PRECISION, DIMENSION(13), INTENT(OUT) :: BF 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
