      MODULE dgetrs_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:54:31  01/16/06  
      SUBROUTINE dgetrs (TRANS, N, NRHS, A, LDA, IPIV, B, LDB, INFO) 
      USE vast_kind_param,ONLY: DOUBLE 
      character (LEN = 1) :: TRANS 
      integer, INTENT(IN) :: N 
      integer, INTENT(IN) :: NRHS 
      integer, INTENT(IN) :: LDA, LDB
      real(DOUBLE), DIMENSION(LDA,*) :: A      
      integer, DIMENSION(*) :: IPIV 
      real(DOUBLE), DIMENSION(LDB,*) :: B       
      integer, INTENT(OUT) :: INFO 
!VAST...Calls: LSAME, DLASWP, DTRSM, XERBLA
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE dgetf2_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:54:31  01/16/06  
      SUBROUTINE dgetf2 (M, N, A, LDA, IPIV) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: M 
      integer, INTENT(IN) :: N 
      integer, INTENT(IN) :: LDA 
      real(DOUBLE), DIMENSION(LDA,*), INTENT(IN) :: A  
      integer, DIMENSION(*), INTENT(OUT) :: IPIV 
!VAST...Calls: IDAMAX, DGER, DSCAL, DSWAP, XERBLA
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
            MODULE dlaswp_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:04  03/09/06  
      SUBROUTINE dlaswp (N, A, LDA, K1, K2, IPIV, INCX) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, intent(in) :: N       
      integer, INTENT(IN) :: LDA 
      integer, INTENT(IN) :: K1 
      integer, INTENT(IN) :: K2 
      integer, DIMENSION(*), INTENT(IN) :: IPIV 
      integer, INTENT(IN) :: INCX 
      real(DOUBLE), intent(inout), DIMENSION(LDA,*) :: A 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
            MODULE dtrsm_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  22:48:56  03/08/06  
      SUBROUTINE dtrsm (SIDE, UPLO, TRANSA, DIAG, M, N, ALPHA, A, LDA, B, LDB) 
      USE vast_kind_param,ONLY: DOUBLE 
      character (LEN = *) :: SIDE 
      character (LEN = *) :: UPLO 
      character (LEN = *) :: TRANSA 
      character (LEN = *) :: DIAG 
      integer, INTENT(IN) :: M 
      integer, INTENT(IN) :: N, LDA, LDB
      real(DOUBLE), INTENT(IN) :: ALPHA 
      real(DOUBLE), DIMENSION(LDA,*), INTENT(IN) :: A 
      real(DOUBLE), DIMENSION(LDB,*), INTENT(INOUT) :: B 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE dgedi_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:10  03/09/06  
      SUBROUTINE dgedi (A, LDA, N, IPVT, det, work,JOB) 
      USE vast_kind_param,ONLY: DOUBLE       
      integer, INTENT(IN) :: LDA 
      integer, INTENT(IN) :: N 
      real(DOUBLE), DIMENSION(LDA,N), INTENT(INOUT) :: A 
      double precision, dimension (2), intent (out) :: det
      double precision, dimension (n), intent (out) :: work
      integer, DIMENSION(N), INTENT(IN) :: IPVT 
      integer, INTENT(IN) :: JOB 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE ieeeck_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:55:50  01/16/06  
      INTEGER FUNCTION ieeeck (ISPEC, ZERO, ONE) 
      integer, INTENT(IN) :: ISPEC 
      real, INTENT(IN) :: ZERO 
      real, INTENT(IN) :: ONE 
      END FUNCTION  
      END INTERFACE 
      END MODULE 

      MODULE idamax_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  22:48:56  03/08/06  
      INTEGER FUNCTION idamax (N, DX, INCX) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: N 
      real(DOUBLE), DIMENSION(*), INTENT(IN) :: DX 
      integer, INTENT(IN) :: INCX 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
      MODULE dger_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  22:48:56  03/08/06  
      SUBROUTINE dger (M, N, ALPHA, X, INCX, Y, INCY, A, LDA) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: M 
      integer, INTENT(IN) :: N, LDA
      real(DOUBLE), INTENT(IN) :: ALPHA 
      real(DOUBLE), DIMENSION(*), INTENT(IN) :: X 
      integer, INTENT(IN) :: INCX 
      real(DOUBLE), DIMENSION(*), INTENT(IN) :: Y 
      integer, INTENT(IN) :: INCY 
      real(DOUBLE), DIMENSION(LDA,*), INTENT(INOUT) :: A 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE dscal_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  22:48:56  03/08/06  
      SUBROUTINE dscal (N, DA, DX, INCX) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: N 
      real(DOUBLE), INTENT(IN) :: DA 
      real(DOUBLE), DIMENSION(*), INTENT(INOUT) :: DX 
      integer, INTENT(IN) :: INCX 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
      MODULE dswap_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  22:48:56  03/08/06  
      SUBROUTINE dswap (N, DX, INCX, DY, INCY) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: N 
      real(DOUBLE), DIMENSION(*), INTENT(INOUT) :: DX 
      integer, INTENT(IN) :: INCX 
      real(DOUBLE), DIMENSION(*), INTENT(INOUT) :: DY 
      integer, INTENT(IN) :: INCY 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
