      MODULE bldsym_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:01  03/09/06  
      SUBROUTINE bldsym (IOPER, IPLACE) 
      INTEGER, INTENT(IN) :: IOPER 
      INTEGER, INTENT(IN) :: IPLACE 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
