      MODULE bmakuf_I   
      INTERFACE
      SUBROUTINE bmakuf (UA, UB, UAB, T, UOLD1, GAB, EIGS, LAST, NORBS, NCLOSE&
        , DIFF, IWFLB, MAXU, BTOL) 
      logical, INTENT(OUT) :: LAST 
      integer, INTENT(IN) :: NORBS 
      integer, INTENT(IN) :: NCLOSE 
      DOUBLE PRECISION, INTENT(OUT) :: DIFF 
      integer, INTENT(IN) :: IWFLB 
      DOUBLE PRECISION, INTENT(OUT) :: MAXU 
      DOUBLE PRECISION, INTENT(IN) :: BTOL 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(IN) :: UA 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(IN) :: UB 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(INOUT) :: UAB 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(IN) :: T 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(INOUT) :: UOLD1 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(IN) :: GAB 
      DOUBLE PRECISION, DIMENSION(NORBS), INTENT(IN) :: EIGS 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
