      MODULE bonds_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  12:47:36  03/10/06  
      SUBROUTINE bonds () 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
