      MODULE cartab_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:02  03/09/06  
      SUBROUTINE cartab 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
