      MODULE ccrep_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  12:41:19  03/10/06  
      SUBROUTINE ccrep (NI, NJ, R, ENUCLR, gab) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: NI 
      integer, INTENT(IN) :: NJ 
      real(DOUBLE), INTENT(INOUT) :: R 
      real(DOUBLE), INTENT(IN) :: GAB 
      real(DOUBLE), INTENT(OUT) :: ENUCLR 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
