      MODULE cdiag_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:02  03/09/06  
      SUBROUTINE cdiag (A, VALUE, VEC, N) 
      INTEGER, INTENT(IN) :: N 
      COMPLEX, DIMENSION(N,*) :: A 
      REAL, DIMENSION(*) :: VALUE 
      COMPLEX, DIMENSION(N,*) :: VEC 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
