      MODULE charvi_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:03  03/09/06  
      REAL(KIND(0.0D0)) FUNCTION charvi (VECTS, JORB, IOPER, R, NVECS) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: NVECS  
      REAL(DOUBLE), DIMENSION(NVECS,NVECS), INTENT(IN) :: VECTS 
      INTEGER, INTENT(IN) :: JORB 
      INTEGER, INTENT(IN) :: IOPER 
      REAL(DOUBLE), DIMENSION(3,3), INTENT(IN) :: R      
      END FUNCTION  
      END INTERFACE 
      END MODULE 
