      MODULE charst_I   
      INTERFACE
      DOUBLE PRECISION FUNCTION charst (VECTS, NTYPE, ISTATE, IOPER, R, NVECS, FIRST) 
      use meci_C, only : nmos, lab 
      INTEGER, INTENT(IN) :: NVECS 
      DOUBLE PRECISION, DIMENSION(NVECS,NMOS), INTENT(IN) :: VECTS 
      INTEGER, DIMENSION(*), INTENT(IN) :: NTYPE 
      INTEGER, INTENT(IN) :: ISTATE 
      INTEGER, INTENT(IN) :: IOPER 
      DOUBLE PRECISION, DIMENSION(3,3), INTENT(IN) :: R 
      LOGICAL :: FIRST 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
