      MODULE chi_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:03  03/09/06  
      SUBROUTINE chi (TOLER, COORD, IOPER, IQUAL) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), INTENT(IN) :: TOLER 
      REAL(DOUBLE), DIMENSION(3,*), INTENT(IN) :: COORD 
      INTEGER, INTENT(IN) :: IOPER 
      INTEGER, INTENT(OUT) :: IQUAL 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
