      MODULE ciint_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:04  03/09/06  
      SUBROUTINE ciint (C34, PQ34) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: C34 
      REAL(DOUBLE), DIMENSION(*), INTENT(INOUT) :: PQ34 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
