      MODULE ciosci_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:04  03/09/06  
      SUBROUTINE ciosci (VECTS, lroot, OSCIL, CONF) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: VECTS 
      REAL(DOUBLE), DIMENSION(3,*), INTENT(INOUT) :: OSCIL 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: CONF 
      integer, intent(in) :: lroot
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
