      MODULE cnvg_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  21:13:27  03/10/06  
      SUBROUTINE cnvg (PNEW, P, P1, NITER, PL) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(1234), INTENT(INOUT) :: PNEW 
      REAL(DOUBLE), DIMENSION(1234), INTENT(INOUT) :: P 
      REAL(DOUBLE), DIMENSION(1234), INTENT(INOUT) :: P1 
      INTEGER, INTENT(IN) :: NITER 
      REAL(DOUBLE), INTENT(OUT) :: PL 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
