      MODULE coe_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:04  03/09/06  
      SUBROUTINE coe (X2, Y2, Z2, NORBI, NORBJ, C, R) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), INTENT(IN) :: X2 
      REAL(DOUBLE), INTENT(IN) :: Y2 
      REAL(DOUBLE), INTENT(IN) :: Z2 
      INTEGER, INTENT(IN) :: NORBI 
      INTEGER, INTENT(IN) :: NORBJ 
      REAL(DOUBLE), DIMENSION(75), INTENT(OUT) :: C 
      REAL(DOUBLE), INTENT(OUT) :: R 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
