      MODULE collis_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:33  03/09/06  
      LOGICAL FUNCTION collis (CW, RW, CNBR, RNBR, NNBR, ISHAPE) 
      USE vast_kind_param,ONLY: DOUBLE 
      real(DOUBLE), DIMENSION(3), INTENT(IN) :: CW 
      real(DOUBLE), INTENT(IN) :: RW 
      real(DOUBLE), DIMENSION(3,200), INTENT(IN) :: CNBR 
      real(DOUBLE), DIMENSION(200), INTENT(IN) :: RNBR 
      integer, INTENT(IN) :: NNBR 
      integer, INTENT(IN) :: ISHAPE 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
