      MODULE compfg_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  09:47:13  03/15/06  
      SUBROUTINE compfg (XPARAM, INT, ESCF, FULSCF, GRAD, LGRAD) 
      USE vast_kind_param,ONLY: DOUBLE  
      REAL(DOUBLE), DIMENSION(*), intent (in) :: XPARAM 
      logical, intent(in) :: INT, fulscf 
      REAL(DOUBLE), intent(out) :: ESCF 
      REAL(DOUBLE), DIMENSION(*) :: GRAD 
      LOGICAL, intent(in) :: LGRAD 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
