      MODULE dang_I   
      INTERFACE
      SUBROUTINE dang (A1, A2, B1, B2, RCOS) 
      DOUBLE PRECISION, INTENT(INOUT) :: A1 
      DOUBLE PRECISION, INTENT(INOUT) :: A2 
      DOUBLE PRECISION, INTENT(INOUT) :: B1 
      DOUBLE PRECISION, INTENT(INOUT) :: B2 
      DOUBLE PRECISION, INTENT(OUT) :: RCOS 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
