      MODULE dang_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  08:33:27  03/09/06  
      SUBROUTINE dang (A1, A2, B1, B2, RCOS) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), INTENT(INOUT) :: A1 
      REAL(DOUBLE), INTENT(INOUT) :: A2 
      REAL(DOUBLE), INTENT(INOUT) :: B1 
      REAL(DOUBLE), INTENT(INOUT) :: B2 
      REAL(DOUBLE), INTENT(OUT) :: RCOS 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
