      MODULE dasum_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  22:48:56  03/08/06  
      REAL(KIND(0.0D0)) FUNCTION dasum (N, DX, INCX) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: N, incx
      REAL(DOUBLE), DIMENSION(INCX*N), INTENT(IN) :: DX 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
