      MODULE dawrit_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  21:23:38  03/14/06  
      SUBROUTINE dawrit (V, LEN, NREC) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: LEN 
      integer, INTENT(IN) :: NREC 
      real(DOUBLE), DIMENSION(LEN) :: V   
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
