      MODULE dcart_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  14:54:27  03/14/06  
      SUBROUTINE dcart (coord, dxyz) 
      USE vast_kind_param, ONLY:  double 
      use molkst_C, only : numat
      real(double), intent(in)  :: coord(3,numat) 
      real(double), intent(out)  :: dxyz(3,numat)   
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
