      MODULE ddpo_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  12:41:19  03/10/06  
      SUBROUTINE ddpo (NI) 
      integer, INTENT(IN) :: NI 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
