      MODULE delmol_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:46:59  03/09/06  
      SUBROUTINE delmol (COORD, I, J, NI, NJ, IA, ID, JA, JD, IX, RIJ, TOMB&
        , ISP) 
      USE vast_kind_param,ONLY: DOUBLE 
      real(DOUBLE), DIMENSION(3,25) :: COORD 
      integer :: I 
      integer :: J 
      integer, INTENT(IN) :: NI 
      integer, INTENT(IN) :: NJ 
      integer, INTENT(IN) :: IA 
      integer, INTENT(IN) :: ID 
      integer, INTENT(IN) :: JA 
      integer, INTENT(IN) :: JD 
      integer :: IX 
      real(DOUBLE) :: RIJ 
      real(DOUBLE) :: TOMB 
      integer, INTENT(INOUT) :: ISP 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
