      MODULE delri_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:46:59  03/09/06  
      SUBROUTINE delri (DG, NI, NJ, RR, DEL1) 
      USE vast_kind_param,ONLY: DOUBLE 
      real(DOUBLE), DIMENSION(22), INTENT(OUT) :: DG 
      integer, INTENT(IN) :: NI 
      integer, INTENT(IN) :: NJ 
      real(DOUBLE), INTENT(IN) :: RR 
      real(DOUBLE), INTENT(IN) :: DEL1 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
