      MODULE delta_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:12  03/09/06  
      INTEGER FUNCTION delta (A, B, C, Y) 
      integer, INTENT(IN) :: A 
      integer, INTENT(IN) :: B 
      integer, INTENT(IN) :: C 
      integer, INTENT(IN) :: Y 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
