      MODULE denrot_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:05  03/09/06  
      SUBROUTINE denrot ()  
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
