      MODULE densf_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  21:23:38  03/14/06  
      SUBROUTINE densf (U, C, D, DA, NORBS, NCLOSE, W2) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: NORBS 
      integer, INTENT(IN) :: NCLOSE
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(IN) :: U 
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(IN) :: C 
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(OUT) :: D 
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(OUT) :: DA 
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(INOUT) :: W2 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
