      MODULE deriv_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  17:57:06  03/12/06  
      SUBROUTINE deriv (GEO, GRAD) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: GEO
      REAL(DOUBLE), DIMENSION(*), INTENT(inOUT) :: grad
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
