      MODULE deri1_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  17:23:45  03/12/06  
      SUBROUTINE deri1 (NUMBER, GRAD, F, MINEAR, fd, SCALAR, work) 
      USE vast_kind_param,ONLY: DOUBLE  
      use molkst_C, only : mpack, norbs   
      INTEGER, INTENT(IN) :: NUMBER 
      REAL(DOUBLE), INTENT(OUT) :: GRAD 
      REAL(DOUBLE), DIMENSION(mpack), INTENT(INOUT) :: F 
      real(double)  :: fd(mpack) 
      real(double), intent(out) :: work(norbs, norbs)
      INTEGER, INTENT(IN) :: MINEAR 
      REAL(DOUBLE), DIMENSION(mpack), INTENT(IN) :: SCALAR 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
