      MODULE deri0_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:06  03/09/06  
      SUBROUTINE deri0 (E, N, SCALAR, DIAG, FRACT, NBO) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: N 
      REAL(DOUBLE), DIMENSION(N), INTENT(IN) :: E       
      REAL(DOUBLE), DIMENSION(*), INTENT(OUT) :: SCALAR 
      REAL(DOUBLE), DIMENSION(*), INTENT(INOUT) :: DIAG 
      REAL(DOUBLE), INTENT(IN) :: FRACT 
      INTEGER, DIMENSION(3), INTENT(IN) :: NBO 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
