      MODULE deri23_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:07  03/09/06  
      SUBROUTINE deri23 (F, FD, E, FCI, CMO, EMO, NINEAR, MINEAR) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT (IN) :: NINEAR, MINEAR
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: F 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: FD 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: E 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: FCI 
      REAL(DOUBLE), DIMENSION(*), INTENT(OUT) :: CMO 
      REAL(DOUBLE), DIMENSION(*) :: EMO 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
