      MODULE deritr_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  17:52:28  03/12/06  
      SUBROUTINE deritr () 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
