      MODULE deri23_I   
      INTERFACE
      SUBROUTINE deri23 (F, FD, E, FCI, CMO, EMO, NINEAR, MINEAR) 
      INTEGER, INTENT (IN) :: NINEAR, MINEAR
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: F 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: FD 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: E 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: FCI 
      DOUBLE PRECISION, DIMENSION(*), INTENT(OUT) :: CMO 
      DOUBLE PRECISION, DIMENSION(*) :: EMO 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
