      MODULE ders_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:46:59  03/09/06  
      SUBROUTINE ders (M, N, RR, DEL1, DEL2, DEL3, IS, IOL) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: M 
      integer, INTENT(IN) :: N 
      real(DOUBLE), INTENT(IN) :: RR 
      real(DOUBLE), INTENT(IN) :: DEL1 
      real(DOUBLE), INTENT(IN) :: DEL2 
      real(DOUBLE), INTENT(IN) :: DEL3 
      integer, INTENT(IN) :: IS 
      integer, INTENT(IN) :: IOL 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
