      MODULE dex2_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:13  03/09/06  
      REAL(KIND(0.0D0)) FUNCTION dex2 (M) 
      integer, INTENT(IN) :: M 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
