      MODULE dfock2_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:07  03/09/06  
      SUBROUTINE dfock2 (F, PTOT, P, W, NUMAT, NFIRST, NLAST, NATI) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(*), INTENT(INOUT) :: F 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: PTOT 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: P 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: W 
      INTEGER, INTENT(IN) :: NUMAT 
      INTEGER, DIMENSION(*), INTENT(IN) :: NFIRST 
      INTEGER, DIMENSION(*), INTENT(IN) :: NLAST 
      INTEGER, INTENT(IN) :: NATI 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
