      MODULE dgefa_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:10  03/09/06  
      SUBROUTINE dgefa (A, LDA, N, IPVT, INFO) 
      USE vast_kind_param,ONLY: DOUBLE
      integer, INTENT(IN) :: LDA 
      integer, INTENT(IN) :: N 
      real(DOUBLE), DIMENSION(LDA,N), INTENT(INOUT) :: A      
      integer, DIMENSION(N), INTENT(OUT) :: IPVT 
      integer, INTENT(OUT) :: INFO 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
