      MODULE dgetri_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:04  03/09/06  
      SUBROUTINE dgetri (N, A, LDA, IPIV, WORK, LWORK) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: N, LDA, LWORK
      real(DOUBLE), DIMENSION(LDA,*), INTENT(INOUT) :: A  
      integer, DIMENSION(*), INTENT(IN) :: IPIV 
      real(DOUBLE), DIMENSION(LWORK), INTENT(OUT) :: WORK 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
