      MODULE dhc_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:07  03/09/06  
      SUBROUTINE dhc (P, PA, PB, XI, NAT, IF, IL, JF, JL, DENER, MODE) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(171), intent(in) :: P, pa, pb
      REAL(DOUBLE), DIMENSION(3,2), INTENT(IN) :: XI 
      INTEGER, DIMENSION(2), INTENT(IN) :: NAT 
      INTEGER, INTENT(IN) :: IF 
      INTEGER, INTENT(IN) :: IL 
      INTEGER, INTENT(IN) :: JF 
      INTEGER, INTENT(IN) :: JL 
      REAL(DOUBLE), INTENT(OUT) :: DENER 
      INTEGER, INTENT(IN) :: MODE 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
