      MODULE dhcore_I   
      INTERFACE
      SUBROUTINE dhcore (COORD, H, W, ENUCLR, NATI, NATX, STEP) 
      DOUBLE PRECISION, DIMENSION(3,*), INTENT(INOUT) :: COORD 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: H 
      DOUBLE PRECISION, DIMENSION(*), INTENT(OUT) :: W 
      DOUBLE PRECISION, INTENT(OUT) :: ENUCLR 
      INTEGER, INTENT(IN) :: NATI 
      INTEGER, INTENT(IN) :: NATX 
      DOUBLE PRECISION, INTENT(IN) :: STEP 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
