      MODULE dhcore_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:08  03/09/06  
      SUBROUTINE dhcore (COORD, H, W, ENUCLR, NATI, NATX, STEP) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(3,*), INTENT(INOUT) :: COORD 
      REAL(DOUBLE), DIMENSION(*), INTENT(INOUT) :: H 
      REAL(DOUBLE), DIMENSION(*), INTENT(OUT) :: W 
      REAL(DOUBLE), INTENT(OUT) :: ENUCLR 
      INTEGER, INTENT(IN) :: NATI 
      INTEGER, INTENT(IN) :: NATX 
      REAL(DOUBLE), INTENT(IN) :: STEP 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
