      MODULE diagi_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:08  03/09/06  
      REAL(KIND(0.0D0)) FUNCTION diagi (IALPHA, IBETA, EIGA, XY, NMOS) 
      USE vast_kind_param,ONLY: DOUBLE 
      use meci_C, only : nmeci 
      INTEGER, INTENT(IN) :: NMOS 
      INTEGER, DIMENSION(NMOS), INTENT(IN) :: IALPHA 
      INTEGER, DIMENSION(NMOS), INTENT(IN) :: IBETA 
      REAL(DOUBLE), DIMENSION(NMECI), INTENT(IN) :: EIGA 
      REAL(DOUBLE), DIMENSION(NMOS,NMOS,NMOS,NMOS), INTENT(IN) :: XY       
      END FUNCTION  
      END INTERFACE 
      END MODULE 
