      MODULE diag_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  14:55:13  03/15/06  
      SUBROUTINE diag (FAO, VECTOR, NOCC, EIG, MDIM, N) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: MDIM 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: FAO 
      REAL(DOUBLE), DIMENSION(MDIM,MDIM), INTENT(INOUT) :: VECTOR 
      INTEGER, INTENT(IN) :: NOCC 
      REAL(DOUBLE), DIMENSION(MDIM), INTENT(IN) :: EIG 
      INTEGER, INTENT(IN) :: N 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
