      MODULE diat2_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:08  03/09/06  
      SUBROUTINE diat2 (NA, ESA, EPA, R12, NB, ESB, EPB, S, A0) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: NA 
      REAL(DOUBLE) :: ESA 
      REAL(DOUBLE) :: EPA 
      REAL(DOUBLE), INTENT(IN) :: R12 
      INTEGER, INTENT(IN) :: NB 
      REAL(DOUBLE) :: ESB 
      REAL(DOUBLE) :: EPB 
      REAL(DOUBLE), DIMENSION(3,3,3), INTENT(INOUT) :: S 
      REAL(DOUBLE), INTENT(IN) :: A0 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
