      MODULE diat_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:08  03/09/06  
      SUBROUTINE diat (NI, NJ, XJ, DI) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: NI 
      INTEGER, INTENT(IN) :: NJ 
      REAL(DOUBLE), DIMENSION(3), INTENT(IN) :: XJ 
      REAL(DOUBLE), DIMENSION(9,9), INTENT(OUT) :: DI 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
