      MODULE diegrd_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  14:15:03  03/10/06  
      subroutine diegrd (dxyz)
      use molkst_C, only: numat
      double precision, dimension (3,numat), intent (inout) :: dxyz 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
