      MODULE dielen_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  14:15:03  03/10/06  
      SUBROUTINE dielen (EDIE) 
      USE vast_kind_param,ONLY: DOUBLE 
      real(DOUBLE), INTENT(OUT) :: EDIE 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
