      MODULE digit_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  09:34:53  03/09/06  
      REAL(KIND(0.0D0)) FUNCTION digit (STRING, ISTART) 
      CHARACTER (LEN = *), INTENT(IN) :: STRING 
      INTEGER, INTENT(IN) :: ISTART 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
