      MODULE dihed_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:09  03/09/06  
      SUBROUTINE dihed (XYZ, I, J, K, L, ANGLE) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(3,*), INTENT(IN) :: XYZ 
      INTEGER, INTENT(IN) :: I, j, k, l 
      REAL(DOUBLE), INTENT(OUT) :: ANGLE 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
