      MODULE dijkl2_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:09  03/09/06  
      SUBROUTINE dijkl2 (DC) 
      USE vast_kind_param,ONLY: DOUBLE       
      use molkst_C, only : norbs
      use meci_C, only : nmos
      REAL(DOUBLE), DIMENSION(NORBS,NMOS) :: DC 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
