      MODULE dijkld_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  12:41:19  03/10/06  
      SUBROUTINE dijkld (C, N, NATI, W, WD, CIJ, WCIJ, CKL, XY) 
      USE vast_kind_param,ONLY: DOUBLE      
      integer, INTENT(IN) :: N 
      integer, INTENT(IN) :: NATI 
      real(DOUBLE), DIMENSION(N,*), INTENT(IN) :: C 
      real(DOUBLE), DIMENSION(*) :: W 
      real(DOUBLE), DIMENSION(*) :: WD 
      real(DOUBLE), DIMENSION(*), INTENT(OUT) :: CIJ 
      real(DOUBLE), DIMENSION(*), INTENT(INOUT) :: WCIJ 
      real(DOUBLE), DIMENSION(*), INTENT(INOUT) :: CKL 
      real(DOUBLE), DIMENSION(*), INTENT(OUT) :: XY 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
