      MODULE dipole_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  09:21:03  03/16/06  
      REAL(KIND(0.0D0)) FUNCTION dipole (P, COORD, DIPVEC, MODE) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: P 
      REAL(DOUBLE), DIMENSION(3,*), INTENT(INOUT) :: COORD 
      REAL(DOUBLE), DIMENSION(3), INTENT(OUT) :: DIPVEC 
      INTEGER, INTENT(IN) :: MODE 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
