      MODULE dist2_I   
      INTERFACE
      DOUBLE PRECISION FUNCTION dist2 (A, B) 
      DOUBLE PRECISION, DIMENSION(3), INTENT(IN) :: A 
      DOUBLE PRECISION, DIMENSION(3), INTENT(IN) :: B 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
