      MODULE dofs_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:10  03/09/06  
      SUBROUTINE dofs (EREF, MONO3, N, DD, M, BOTTOM, TOP) 
      USE vast_kind_param,ONLY: DOUBLE       
      INTEGER, INTENT(IN) :: MONO3 
      INTEGER, INTENT(IN) :: N       
      INTEGER, INTENT(IN) :: M 
      REAL(DOUBLE), DIMENSION(MONO3,N), INTENT(INOUT) :: EREF 
      REAL(DOUBLE), DIMENSION(M), INTENT(INOUT) :: DD 
      REAL(DOUBLE), INTENT(IN) :: BOTTOM 
      REAL(DOUBLE), INTENT(IN) :: TOP 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
