      MODULE dopen_I   
      INTERFACE
      SUBROUTINE dopen (C, MDIM, NORBS, NDUBL, NSINGL, FRACT, SDM) 
      INTEGER, INTENT(IN) :: MDIM 
      INTEGER, INTENT(IN) :: NORBS 
      INTEGER, INTENT(IN) :: NDUBL 
      INTEGER, INTENT(IN) :: NSINGL 
      DOUBLE PRECISION, INTENT(IN) :: FRACT 
      DOUBLE PRECISION, DIMENSION(MDIM,MDIM), INTENT(IN) :: C 
      DOUBLE PRECISION, DIMENSION((MDIM*(MDIM + 1))/2), INTENT(OUT) :: SDM 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
