      MODULE drc_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:10  03/09/06  
      SUBROUTINE drc (STARTV, STARTK) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(*), intent(in) :: STARTV 
      REAL(DOUBLE), DIMENSION(*), intent(in) :: STARTK 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
