      MODULE drcout_I   
      INTERFACE
      SUBROUTINE drcout (XYZ3, GEO3, VEL3, NVAR, TIME, ESCF3, EKIN3, ETOT3&
        , XTOT3, ILOOP, CHARGE, FRACT, TEXT1, TEXT2, II, JLOOP) 
      INTEGER, INTENT(IN) :: NVAR 
      DOUBLE PRECISION, DIMENSION(3,NVAR), INTENT(IN) :: XYZ3 
      DOUBLE PRECISION, DIMENSION(3,*), INTENT(IN) :: GEO3 
      DOUBLE PRECISION, DIMENSION(3,NVAR), INTENT(IN) :: VEL3       
      DOUBLE PRECISION, INTENT(IN) :: TIME 
      DOUBLE PRECISION, DIMENSION(3), INTENT(IN) :: ESCF3 
      DOUBLE PRECISION, DIMENSION(3), INTENT(IN) :: EKIN3 
      DOUBLE PRECISION, DIMENSION(3), INTENT(IN) :: ETOT3 
      DOUBLE PRECISION, DIMENSION(3), INTENT(IN) :: XTOT3 
      INTEGER, INTENT(IN) :: ILOOP 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: CHARGE 
      DOUBLE PRECISION, INTENT(IN) :: FRACT 
      CHARACTER (LEN = 3), INTENT(IN) :: TEXT1 
      CHARACTER (LEN = 2), INTENT(IN) :: TEXT2 
      INTEGER, INTENT(IN) :: II 
      INTEGER, INTENT(INOUT) :: JLOOP 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
