      MODULE drotat_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:33  03/09/06  
      SUBROUTINE drotat (NI, XI, XJ, E1B, ENUC, RIJ) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: NI 
      real(DOUBLE), DIMENSION(3), INTENT(IN) :: XI 
      real(DOUBLE), DIMENSION(3), INTENT(IN) :: XJ 
      real(DOUBLE), DIMENSION(10), INTENT(OUT) :: E1B 
      real(DOUBLE), INTENT(OUT) :: ENUC 
      real(DOUBLE), INTENT(IN) :: RIJ 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
