      MODULE drotat_I   
      INTERFACE
      SUBROUTINE drotat (NI, XI, XJ, E1B, ENUC, RIJ) 
      integer, INTENT(IN) :: NI 
      DOUBLE PRECISION, DIMENSION(3), INTENT(IN) :: XI 
      DOUBLE PRECISION, DIMENSION(3), INTENT(IN) :: XJ 
      DOUBLE PRECISION, DIMENSION(10), INTENT(OUT) :: E1B 
      DOUBLE PRECISION, INTENT(OUT) :: ENUC 
      DOUBLE PRECISION, INTENT(IN) :: RIJ 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
