      MODULE dtran2_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  09:48:01  03/09/06  
      SUBROUTINE dtran2 (R, T, IOPER) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(3,3), INTENT(INout) :: R 
      REAL(DOUBLE), DIMENSION(5,5,12), INTENT(inOUT) :: T 
      INTEGER, INTENT(IN) :: IOPER 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
