      MODULE dtran2_I   
      INTERFACE
      SUBROUTINE dtran2 (R, T, IOPER) 
      DOUBLE PRECISION, DIMENSION(3,3), INTENT(INout) :: R 
      DOUBLE PRECISION, DIMENSION(5,5,12), INTENT(inOUT) :: T 
      INTEGER, INTENT(IN) :: IOPER 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
