      MODULE dvfill_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:04  03/09/06  
      SUBROUTINE dvfill (NPPA, DIRVEC) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: NPPA 
      real(DOUBLE), DIMENSION(3,*), INTENT(INOUT) :: DIRVEC 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
