      MODULE ef_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  12:12:16  03/10/06  
      SUBROUTINE ef (XPARAM, FUNCT) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), intent (inout) :: XPARAM(*) 
      REAL(DOUBLE), intent (inout) :: FUNCT 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
