      MODULE einvit_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:04:14  03/09/06  
      SUBROUTINE einvit (NM, N, D, E, E2, M, W, IND, Z, IERR, RV1, RV2, RV3&
        , RV4, RV6) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: NM 
      integer, INTENT(IN) :: N 
      real(DOUBLE), DIMENSION(N), INTENT(IN) :: D 
      real(DOUBLE), DIMENSION(N + 1), INTENT(IN) :: E 
      real(DOUBLE), DIMENSION(N), INTENT(IN) :: E2 
      integer, INTENT(IN) :: M 
      real(DOUBLE), DIMENSION(M), INTENT(IN) :: W 
      integer, DIMENSION(M), INTENT(IN) :: IND 
      real(DOUBLE), DIMENSION(NM,M), INTENT(OUT) :: Z 
      integer, INTENT(OUT) :: IERR 
      real(DOUBLE), DIMENSION(N), INTENT(INOUT) :: RV1, rv2, rv3, rv4, rv6
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
