      MODULE eiscor_I   
      INTERFACE
      SUBROUTINE eiscor (R016, R066, R244, R266, R466, NI) 
      DOUBLE PRECISION, INTENT(IN) :: R016 
      DOUBLE PRECISION, INTENT(IN) :: R066 
      DOUBLE PRECISION, INTENT(IN) :: R244 
      DOUBLE PRECISION, INTENT(IN) :: R266 
      DOUBLE PRECISION, INTENT(IN) :: R466 
      integer, INTENT(IN) :: NI 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
