      MODULE eiscor_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  12:41:19  03/10/06  
      SUBROUTINE eiscor (R016, R066, R244, R266, R466, NI) 
      USE vast_kind_param,ONLY: DOUBLE 
      real(DOUBLE), INTENT(IN) :: R016 
      real(DOUBLE), INTENT(IN) :: R066 
      real(DOUBLE), INTENT(IN) :: R244 
      real(DOUBLE), INTENT(IN) :: R266 
      real(DOUBLE), INTENT(IN) :: R466 
      integer, INTENT(IN) :: NI 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
