      MODULE en_I   
      INTERFACE
      SUBROUTINE en (XPARAM, NVAR, FUNCT, HESS, PMAT, BMAT, OLDHSS, OLDU, U, UC&
        , HESSC) 
      integer, INTENT(IN) :: NVAR  
      DOUBLE PRECISION, DIMENSION(nvar), INTENT(INOUT) :: XPARAM      
      DOUBLE PRECISION, INTENT(IN) :: FUNCT 
      DOUBLE PRECISION, DIMENSION(NVAR,NVAR), INTENT(INOUT) :: HESS 
      DOUBLE PRECISION, DIMENSION(NVAR*NVAR) :: PMAT 
      DOUBLE PRECISION, DIMENSION(NVAR,NVAR) :: BMAT 
      DOUBLE PRECISION, DIMENSION(NVAR,NVAR), INTENT(INOUT) :: OLDHSS 
      DOUBLE PRECISION, DIMENSION(NVAR,NVAR), INTENT(INOUT) :: OLDU 
      DOUBLE PRECISION, DIMENSION(NVAR,NVAR), INTENT(INOUT) :: U 
      DOUBLE PRECISION, DIMENSION(NVAR*NVAR), INTENT(IN) :: UC 
      DOUBLE PRECISION, DIMENSION(*), INTENT(OUT) :: HESSC 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
