      MODULE en_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  12:12:16  03/10/06  
      SUBROUTINE en (XPARAM, NVAR, FUNCT, HESS, PMAT, BMAT, OLDHSS, OLDU, U, UC&
        , HESSC) 
      USE vast_kind_param,ONLY: DOUBLE
      integer, INTENT(IN) :: NVAR  
      real(DOUBLE), DIMENSION(nvar), INTENT(INOUT) :: XPARAM      
      real(DOUBLE), INTENT(IN) :: FUNCT 
      real(DOUBLE), DIMENSION(NVAR,NVAR), INTENT(INOUT) :: HESS 
      real(DOUBLE), DIMENSION(NVAR*NVAR) :: PMAT 
      real(DOUBLE), DIMENSION(NVAR,NVAR) :: BMAT 
      real(DOUBLE), DIMENSION(NVAR,NVAR), INTENT(INOUT) :: OLDHSS 
      real(DOUBLE), DIMENSION(NVAR,NVAR), INTENT(INOUT) :: OLDU 
      real(DOUBLE), DIMENSION(NVAR,NVAR), INTENT(INOUT) :: U 
      real(DOUBLE), DIMENSION(NVAR*NVAR), INTENT(IN) :: UC 
      real(DOUBLE), DIMENSION(*), INTENT(OUT) :: HESSC 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
