      MODULE enpart_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:12  03/09/06  
      SUBROUTINE enpart () 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
