      MODULE epsab_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  21:23:38  03/14/06  
      SUBROUTINE epsab (EIGSAB, EIGS, GAB, GA, GB, UA, UB, UAB, UDMS, NORBS&
        , NCLOSE, IWFLB) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: NORBS 
      integer, INTENT(IN) :: NCLOSE 
      integer, INTENT(IN) :: IWFLB 
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(OUT) :: EIGSAB 
      real(DOUBLE), DIMENSION(NORBS), INTENT(IN) :: EIGS 
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(IN) :: GAB 
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(IN) :: GA 
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(IN) :: GB 
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(IN) :: UA 
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(IN) :: UB 
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(IN) :: UAB 
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(OUT) :: UDMS 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
