      MODULE epsab_I   
      INTERFACE
      SUBROUTINE epsab (EIGSAB, EIGS, GAB, GA, GB, UA, UB, UAB, UDMS, NORBS&
        , NCLOSE, IWFLB) 
      integer, INTENT(IN) :: NORBS 
      integer, INTENT(IN) :: NCLOSE 
      integer, INTENT(IN) :: IWFLB 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(OUT) :: EIGSAB 
      DOUBLE PRECISION, DIMENSION(NORBS), INTENT(IN) :: EIGS 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(IN) :: GAB 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(IN) :: GA 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(IN) :: GB 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(IN) :: UA 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(IN) :: UB 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(IN) :: UAB 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(OUT) :: UDMS 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
