      MODULE epseta_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  08:34:01  03/09/06  
      SUBROUTINE epseta (EPS, ETA) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), INTENT(OUT) :: EPS 
      REAL(DOUBLE), INTENT(OUT) :: ETA 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
