      MODULE epslon_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:04:14  03/09/06  
      REAL(KIND(0.0D0)) FUNCTION epslon (X) 
      USE vast_kind_param,ONLY: DOUBLE 
      real(DOUBLE), INTENT(IN) :: X 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
