      MODULE eqlrat_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:04:14  03/09/06  
      SUBROUTINE eqlrat (N, DIAG, E, E2IN, D, IND, IERR, E2) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: N 
      real(DOUBLE), DIMENSION(N), INTENT(IN) :: DIAG 
      real(DOUBLE), DIMENSION(N), INTENT(IN) :: E 
      real(DOUBLE), DIMENSION(N), INTENT(INOUT) :: E2IN 
      real(DOUBLE), DIMENSION(N), INTENT(INOUT) :: D 
      integer, DIMENSION(N), INTENT(OUT) :: IND 
      integer, INTENT(OUT) :: IERR 
      real(DOUBLE), DIMENSION(N), INTENT(INOUT) :: E2 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
