      MODULE eqlrat_I   
      INTERFACE
      SUBROUTINE eqlrat (N, DIAG, E, E2IN, D, IND, IERR, E2) 
      integer, INTENT(IN) :: N 
      DOUBLE PRECISION, DIMENSION(N), INTENT(IN) :: DIAG 
      DOUBLE PRECISION, DIMENSION(N), INTENT(IN) :: E 
      DOUBLE PRECISION, DIMENSION(N), INTENT(INOUT) :: E2IN 
      DOUBLE PRECISION, DIMENSION(N), INTENT(INOUT) :: D 
      integer, DIMENSION(N), INTENT(OUT) :: IND 
      integer, INTENT(OUT) :: IERR 
      DOUBLE PRECISION, DIMENSION(N), INTENT(INOUT) :: E2 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
