      MODULE estpi1_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:04:14  03/09/06  
      REAL(KIND(0.0D0)) FUNCTION estpi1 (N, EVAL, D, E, X, ANORM) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: N 
      real(DOUBLE), INTENT(IN) :: EVAL 
      real(DOUBLE), DIMENSION(N), INTENT(IN) :: D, e, x
      real(DOUBLE), INTENT(INOUT) :: ANORM 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
