      MODULE estpi1_I   
      INTERFACE
      DOUBLE PRECISION FUNCTION estpi1 (N, EVAL, D, E, X, ANORM) 
      integer, INTENT(IN) :: N 
      DOUBLE PRECISION, INTENT(IN) :: EVAL 
      DOUBLE PRECISION, DIMENSION(N), INTENT(IN) :: D, e, x
      DOUBLE PRECISION, INTENT(INOUT) :: ANORM 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
