      MODULE etime_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:16  03/09/06  
      SUBROUTINE etime (CPU) 
      REAL, DIMENSION(2), INTENT(OUT) :: CPU 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
