      MODULE etred3_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:04:14  03/09/06  
      SUBROUTINE etred3 (N, A, D, E, E2) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: N 
      real(DOUBLE), DIMENSION(*), INTENT(INOUT) :: A 
      real(DOUBLE), DIMENSION(*), INTENT(OUT) :: D, e, e2
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
