      MODULE evvrsp_I   
      INTERFACE
      SUBROUTINE evvrsp (MSGFL, N, NVECT, LENA, NV, A, ROOT, VECT&
        , IORDER, IERR) 
      INTEGER, INTENT(IN) :: MSGFL 
      INTEGER, INTENT(IN) :: N 
      INTEGER, INTENT(IN) :: NVECT 
      INTEGER, INTENT(IN) :: LENA 
      INTEGER, INTENT(IN) :: NV 
      DOUBLE PRECISION, DIMENSION(LENA) :: A  
      DOUBLE PRECISION, DIMENSION(N), INTENT(INOUT) :: ROOT 
      DOUBLE PRECISION, DIMENSION(NV,*) :: VECT 
      INTEGER, INTENT(IN) :: IORDER 
      INTEGER, INTENT(OUT) :: IERR 
      END SUBROUTINE 
      END INTERFACE 
      END MODULE 
