      MODULE evvrsp_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:04:14  03/09/06  
      SUBROUTINE evvrsp (MSGFL, N, NVECT, LENA, NV, A, ROOT, VECT&
        , IORDER, IERR) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: MSGFL 
      INTEGER, INTENT(IN) :: N 
      INTEGER, INTENT(IN) :: NVECT 
      INTEGER, INTENT(IN) :: LENA 
      INTEGER, INTENT(IN) :: NV 
      REAL(DOUBLE), DIMENSION(LENA) :: A  
      REAL(DOUBLE), DIMENSION(N), INTENT(INOUT) :: ROOT 
      REAL(DOUBLE), DIMENSION(NV,*) :: VECT 
      INTEGER, INTENT(IN) :: IORDER 
      INTEGER, INTENT(OUT) :: IERR 
      END SUBROUTINE 
      END INTERFACE 
      END MODULE 
