      MODULE exchng_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  08:34:14  03/09/06  
      SUBROUTINE exchng (A, B, C, D, X, Y, T, Q, N) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), INTENT(IN) :: A 
      REAL(DOUBLE), INTENT(OUT) :: B 
      REAL(DOUBLE), INTENT(IN) :: C 
      REAL(DOUBLE), INTENT(OUT) :: D 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: X 
      REAL(DOUBLE), DIMENSION(*), INTENT(OUT) :: Y 
      REAL(DOUBLE), INTENT(IN) :: T 
      REAL(DOUBLE), INTENT(OUT) :: Q 
      INTEGER, INTENT(IN) :: N 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
