      MODULE fcnpp_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:18  03/09/06  
      SUBROUTINE fcnpp (P) 
      USE vast_kind_param,ONLY: DOUBLE 
      real(DOUBLE), DIMENSION(*), INTENT(IN) :: P 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
