      MODULE ffreq2_I   
      INTERFACE
      SUBROUTINE ffreq2 (F, PTOT, W) 
      use molkst_C, only : norbs
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(INOUT) :: F 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(IN) :: PTOT 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: W  
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
