      MODULE ffreq1_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  21:23:38  03/14/06  
      SUBROUTINE ffreq1 (F, PTOT, PA, PB, NDIM) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: NDIM 
      real(DOUBLE), DIMENSION(NDIM,NDIM), INTENT(INOUT) :: F 
      real(DOUBLE), DIMENSION(NDIM,NDIM), INTENT(IN) :: PTOT 
      real(DOUBLE), DIMENSION(NDIM,NDIM), INTENT(IN) :: PA 
      real(DOUBLE), DIMENSION(NDIM,NDIM), INTENT(IN) :: PB       
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
