      MODULE fhpatn_I   
      INTERFACE
      SUBROUTINE fhpatn (A, B, NORBS, ITW, SIGN) 
      integer, INTENT(IN) :: NORBS 
      integer, INTENT(IN) :: ITW 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(OUT) :: A 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(IN) :: B      
      DOUBLE PRECISION, INTENT(IN) :: SIGN 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
