      MODULE flepo_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:14  03/09/06  
      SUBROUTINE flepo (XPARAM, NVAR, FUNCT1) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: NVAR
      REAL(DOUBLE), DIMENSION(NVAR) :: XPARAM        
      REAL(DOUBLE) :: FUNCT1 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
