      MODULE fock1_I   
      INTERFACE
      SUBROUTINE fock1 (F, PTOT, PA, PB) 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: F 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: PTOT 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: PA 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: PB 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
