      MODULE fockd2_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  12:41:19  03/10/06  
      SUBROUTINE fockd2 (F, PTOT, P, W, LMW, WJ, WK, NUMAT, NFIRST, NLAST, NW) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: LMW, NUMAT 
      real(DOUBLE), DIMENSION(*), INTENT(INOUT) :: F 
      real(DOUBLE), DIMENSION(*), INTENT(IN) :: PTOT 
      real(DOUBLE), DIMENSION(*), INTENT(IN) :: P 
      real(DOUBLE), DIMENSION(LMW,LMW), INTENT(IN) :: W       
      real(DOUBLE), DIMENSION(*), INTENT(IN) :: WJ 
      real(DOUBLE), DIMENSION(*), INTENT(IN) :: WK 
      integer, DIMENSION(NUMAT), INTENT(IN) :: NFIRST 
      integer, DIMENSION(NUMAT), INTENT(IN) :: NLAST 
      integer, DIMENSION(NUMAT), INTENT(IN) :: NW 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
