      MODULE formxy_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:15  03/09/06  
      SUBROUTINE formxy (W, KR, WCA, WCB, CA, NA, CB, NB) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(100), INTENT(IN) :: W 
      INTEGER, INTENT(INOUT) :: KR
      INTEGER, INTENT(IN) :: NA, NB 
      REAL(DOUBLE), DIMENSION(NA), INTENT(INOUT) :: WCA 
      REAL(DOUBLE), DIMENSION(NB), INTENT(INOUT) :: WCB 
      REAL(DOUBLE), DIMENSION(NA), INTENT(IN) :: CA        
      REAL(DOUBLE), DIMENSION(NB), INTENT(IN) :: CB 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
