      MODULE frame_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:15  03/09/06  
      SUBROUTINE frame (FMAT, NUMAT, MODE) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(*), INTENT(INOUT) :: FMAT 
      INTEGER, INTENT(IN) :: NUMAT 
      INTEGER, INTENT(IN) :: MODE 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
