      MODULE freda_I   
      INTERFACE
      SUBROUTINE freda (L, D, A, E) 
      integer, INTENT(IN) :: L 
      DOUBLE PRECISION, DIMENSION(L), INTENT(IN) :: D 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: A 
      DOUBLE PRECISION, DIMENSION(L), INTENT(IN) :: E 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
