      MODULE fsub_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:13  03/09/06  
      SUBROUTINE fsub (N, X, FVAL) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: N 
      real(DOUBLE), INTENT(IN) :: X 
      real(DOUBLE), INTENT(OUT) :: FVAL 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
