      MODULE genun_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:16  03/09/06  
      SUBROUTINE genun (U, N) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(INOUT) :: N 
      REAL(DOUBLE), DIMENSION(3,N), INTENT(OUT) :: U       
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
