      MODULE genvec_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:33  03/09/06  
      SUBROUTINE genvec (U, N) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(INOUT) :: N
      real(DOUBLE), DIMENSION(3,N), INTENT(OUT) :: U        
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
