      MODULE geout_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  08:50:09  03/09/06  
      SUBROUTINE geout (MODE1) 
      INTEGER, INTENT(IN) :: MODE1 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
