      MODULE geoutg_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:16  03/09/06  
      SUBROUTINE geoutg (IPRT) 
      INTEGER, INTENT(IN) :: IPRT 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
