      MODULE getgeg_I   
      INTERFACE
      SUBROUTINE getgeg (IREAD, LABELS, GEO, LOPT, NA, NB, NC) 
      INTEGER, INTENT(IN) :: IREAD 
      INTEGER, DIMENSION(*), INTENT(OUT) :: LABELS 
      DOUBLE PRECISION, DIMENSION(3,*), INTENT(INOUT) :: GEO 
      INTEGER, DIMENSION(3,*), INTENT(OUT) :: LOPT 
      INTEGER, DIMENSION(*), INTENT(OUT) :: NA 
      INTEGER, DIMENSION(*), INTENT(OUT) :: NB 
      INTEGER, DIMENSION(*), INTENT(OUT) :: NC 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
