      MODULE getgeg_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:16  03/09/06  
      SUBROUTINE getgeg (IREAD, LABELS, GEO, LOPT, NA, NB, NC) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: IREAD 
      INTEGER, DIMENSION(*), INTENT(OUT) :: LABELS 
      REAL(DOUBLE), DIMENSION(3,*), INTENT(INOUT) :: GEO 
      INTEGER, DIMENSION(3,*), INTENT(OUT) :: LOPT 
      INTEGER, DIMENSION(*), INTENT(OUT) :: NA 
      INTEGER, DIMENSION(*), INTENT(OUT) :: NB 
      INTEGER, DIMENSION(*), INTENT(OUT) :: NC 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
