      MODULE getgeo_I   
      INTERFACE
      SUBROUTINE getgeo (IREAD, LABELS, GEO, XYZ, LOPT, NA, NB, NC, int) 
      INTEGER, INTENT(IN) :: IREAD 
      INTEGER, DIMENSION(*), INTENT(OUT) :: LABELS 
      DOUBLE PRECISION, DIMENSION(3,*), INTENT(OUT) :: GEO, XYZ
      INTEGER, DIMENSION(3,*), INTENT(OUT) :: LOPT 
      INTEGER, DIMENSION(*), INTENT(OUT) :: NA 
      INTEGER, DIMENSION(*), INTENT(OUT) :: NB 
      INTEGER, DIMENSION(*), INTENT(OUT) :: NC 
      logical, intent(out) :: int
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
