      MODULE gettxt_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:18  03/09/06  
      SUBROUTINE gettxt 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
