      MODULE getval_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  08:34:32  03/09/06  
      SUBROUTINE getval (LINE, X, T) 
      USE vast_kind_param,ONLY: DOUBLE 
      CHARACTER (LEN = 80), INTENT(IN) :: LINE 
      REAL(DOUBLE), INTENT(OUT) :: X 
      CHARACTER (LEN = 12), INTENT(OUT) :: T 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
