      MODULE gmetry_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:18  03/09/06  
      SUBROUTINE gmetry (GEO, COORD) 
      USE vast_kind_param,ONLY: DOUBLE 
      use molkst_C, only : natoms      
      REAL(DOUBLE), DIMENSION(3,NATOMS) :: GEO 
      REAL(DOUBLE), DIMENSION(3,NATOMS), INTENT(OUT) :: COORD 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
