      MODULE gover_I   
      INTERFACE
      SUBROUTINE gover (NI, NJ, XJ, R, SG, A0) 
      INTEGER, INTENT(IN) :: NI 
      INTEGER, INTENT(IN) :: NJ 
      DOUBLE PRECISION, DIMENSION(3), INTENT(IN) :: XJ 
      DOUBLE PRECISION, INTENT(INOUT) :: R 
      DOUBLE PRECISION, DIMENSION(9,9), INTENT(INOUT) :: SG 
      DOUBLE PRECISION, INTENT(IN) :: A0 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
