      MODULE gstore_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:18  03/09/06  
      SUBROUTINE gstore (II, JJ, KK, LL, WERT, PGR) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: II 
      INTEGER, INTENT(IN) :: JJ 
      INTEGER, INTENT(IN) :: KK 
      INTEGER, INTENT(IN) :: LL 
      REAL(DOUBLE), INTENT(IN) :: WERT 
      REAL(DOUBLE), DIMENSION(*), INTENT(OUT) :: PGR 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
