      MODULE h1elec_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:20  03/09/06  
      SUBROUTINE h1elec (NI, NJ, XI, XJ, SMAT) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: NI 
      INTEGER, INTENT(IN) :: NJ 
      REAL(DOUBLE), DIMENSION(3), INTENT(IN) :: XI 
      REAL(DOUBLE), DIMENSION(3), INTENT(IN) :: XJ 
      REAL(DOUBLE), DIMENSION(9,9), INTENT(OUT) :: SMAT 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
