      MODULE haddon_I   
      INTERFACE
      SUBROUTINE haddon (W, L, M, LOC, A, FACT) 
      DOUBLE PRECISION, INTENT(OUT) :: W 
      INTEGER, INTENT(OUT) :: L 
      INTEGER, INTENT(IN) :: M 
      INTEGER, INTENT(IN) :: LOC 
      DOUBLE PRECISION, DIMENSION(3,*), INTENT(IN) :: A 
      DOUBLE PRECISION, INTENT(IN) :: FACT 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
