      MODULE hcore_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  15:30:15  03/09/06  
      SUBROUTINE hcore () 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
