      MODULE helect_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  08:34:42  03/09/06  
      REAL(KIND(0.0D0)) FUNCTION helect (N, P, H, F) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: N 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: P 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: H 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: F 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
