      MODULE hmuf_I   
      INTERFACE
      SUBROUTINE hmuf (H1, ID, COORD, NFIRST, NLAST, NAT, NORBS, NUMAT) 
      integer, INTENT(IN) :: ID 
      integer, INTENT(IN) :: NORBS 
      integer, INTENT(IN) :: NUMAT 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(INOUT) :: H1 
      DOUBLE PRECISION, DIMENSION(3,*), INTENT(IN) :: COORD 
      integer, DIMENSION(NUMAT), INTENT(IN) :: NFIRST 
      integer, DIMENSION(NUMAT), INTENT(IN) :: NLAST 
      integer, DIMENSION(NUMAT), INTENT(IN) :: NAT 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
