      MODULE hplusf_I   
      INTERFACE
      SUBROUTINE hplusf (F, H, NORBS) 
      integer, INTENT(IN) :: NORBS  
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(INOUT) :: F 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(IN) :: H       
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
