      MODULE initsv_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  14:15:03  03/10/06  
      SUBROUTINE initsv (INDEPS) 
      integer :: INDEPS 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
