      MODULE interp_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:21  03/09/06  
    subroutine interp(np, nq, mode, e, fp, cp, theta, vec_interp, fock_interp, &
     p_interp, h_interp, vecl, eold_ref) 
!-----------------------------------------------
!   M o d u l e s 
!-----------------------------------------------
      use molkst_C, only : norbs
      integer, intent(in) :: np, nq
      integer , intent(inout) :: mode 
      double precision , intent(in) :: e 
      double precision , intent(in) :: fp((norbs*(norbs + 1))/2) 
      double precision , intent(inout) :: cp(norbs,norbs) 
      double precision , dimension (norbs, norbs), intent (inout) :: vec_interp, &
    & fock_interp, p_interp
      double precision , dimension (norbs*norbs), intent (inout) :: h_interp
      double precision, dimension(norbs), intent (inout) :: theta 
      double precision, intent (inout)  :: vecl(norbs*norbs)
      double precision, intent(inout) :: eold_ref
!-----------------------------------------------
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
