      MODULE intfc_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:21  03/09/06  
      SUBROUTINE intfc (FMATRX, XPARAM, GEOREF, NAR, NBR, NCR) 
      USE vast_kind_param,ONLY: DOUBLE 
      use molkst_C, only : nvar, natoms
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: FMATRX 
      REAL(DOUBLE), DIMENSION(NVAR), INTENT(OUT) :: XPARAM 
      REAL(DOUBLE), DIMENSION(3,NATOMS), INTENT(IN) :: GEOREF 
      INTEGER, DIMENSION(NATOMS), INTENT(IN) :: NAR 
      INTEGER, DIMENSION(NATOMS), INTENT(IN) :: NBR 
      INTEGER, DIMENSION(NATOMS), INTENT(IN) :: NCR 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
