      MODULE ird_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:12  03/09/06  
      INTEGER FUNCTION ird (INTVAL, DENOM) 
      integer, INTENT(IN) :: INTVAL 
      integer, INTENT(IN) :: DENOM 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
