      MODULE iten_I   
      INTERFACE
      SUBROUTINE iten (H, W, WJ, WK, EE, FULSCF, RAND, F, FB, P, PA, PB, CBETA&
        , POLD, POLD2, POLD3, PBOLD, PBOLD2, PBOLD3, PGASA, PGASB, PSONA, PSONB) 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: H 
      DOUBLE PRECISION, DIMENSION(*) :: W 
      DOUBLE PRECISION, DIMENSION(*) :: WJ 
      DOUBLE PRECISION, DIMENSION(*) :: WK 
      DOUBLE PRECISION, INTENT(INOUT) :: EE 
      LOGICAL, INTENT(IN) :: FULSCF 
      LOGICAL, INTENT(IN) :: RAND 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: F 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: FB 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: P 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: PA 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: PB 
      DOUBLE PRECISION, DIMENSION(*) :: CBETA 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: POLD 
      DOUBLE PRECISION, DIMENSION(*), INTENT(OUT) :: POLD2 
      DOUBLE PRECISION, DIMENSION(*) :: POLD3 
      DOUBLE PRECISION, DIMENSION(*), INTENT(OUT) :: PBOLD 
      DOUBLE PRECISION, DIMENSION(*), INTENT(OUT) :: PBOLD2 
      DOUBLE PRECISION, DIMENSION(*) :: PBOLD3 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: PGASA 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: PGASB 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: PSONA 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: PSONB 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
