      MODULE iter_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:42:48  03/15/06  
      SUBROUTINE iter (EE, FULSCF, RAND) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), intent(out) :: EE 
      logical, intent(in) :: FULSCF, RAND 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
