      MODULE jab_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:22  03/09/06  
      SUBROUTINE jab (IA, JA, PJA, PJB, W, F) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: IA 
      INTEGER, INTENT(IN) :: JA 
      REAL(DOUBLE), DIMENSION(16), INTENT(IN) :: PJA 
      REAL(DOUBLE), DIMENSION(16), INTENT(IN) :: PJB 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: W 
      REAL(DOUBLE), DIMENSION(*), INTENT(INOUT) :: F 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
