      MODULE jcarin_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:22  03/09/06  
      SUBROUTINE jcarin (XPARAM, STEP, PRECI, B, NCOL, IL, IU) 
      USE vast_kind_param,ONLY: DOUBLE 
      real(double), intent(in) :: step
      logical, intent(in) :: preci
      integer, intent(in) :: il, iu
      integer, intent(out) :: ncol
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: XPARAM 
      REAL(DOUBLE), DIMENSION(*), INTENT(INOUT) :: B 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
