      MODULE kab_I   
      INTERFACE
      SUBROUTINE kab (IA, JA, PK, W, F) 
      INTEGER, INTENT(IN) :: IA 
      INTEGER, INTENT(IN) :: JA 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: PK 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: W 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: F 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
