      MODULE kab_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:22  03/09/06  
      SUBROUTINE kab (IA, JA, PK, W, F) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: IA 
      INTEGER, INTENT(IN) :: JA 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: PK 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: W 
      REAL(DOUBLE), DIMENSION(*), INTENT(INOUT) :: F 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
