      MODULE linmin_I   
      INTERFACE
      SUBROUTINE linmin (XPARAM, ALPHA, PVECT, NVAR, FUNCT, OKF, IC, DOTT) 
      INTEGER, INTENT(IN) :: NVAR 
      DOUBLE PRECISION, DIMENSION(NVAR), INTENT(INOUT) :: XPARAM 
      DOUBLE PRECISION, INTENT(OUT) :: ALPHA 
      DOUBLE PRECISION, DIMENSION(NVAR), INTENT(INOUT) :: PVECT       
      DOUBLE PRECISION, INTENT(IN) :: FUNCT 
      LOGICAL, INTENT(INOUT) :: OKF 
      INTEGER, INTENT(INOUT) :: IC 
      DOUBLE PRECISION, INTENT(IN) :: DOTT 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
