      MODULE locmin_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:23  03/09/06  
      SUBROUTINE locmin (M, X, N, P, SSQ, ALF, EFS, ncount) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: M, n 
      REAL(DOUBLE), DIMENSION(*), INTENT(INOUT) :: X 
      INTEGER :: Ncount
      REAL(DOUBLE), DIMENSION(*), INTENT(INOUT) :: P 
      REAL(DOUBLE), INTENT(INOUT) :: SSQ 
      REAL(DOUBLE), INTENT(INOUT) :: ALF 
      REAL(DOUBLE), DIMENSION(*), INTENT(INOUT) :: EFS 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
