      MODULE locmin_I   
      INTERFACE
      SUBROUTINE locmin (M, X, N, P, SSQ, ALF, EFS, ncount) 
      INTEGER, INTENT(IN) :: M, n 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: X 
      INTEGER :: Ncount
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: P 
      DOUBLE PRECISION, INTENT(INOUT) :: SSQ 
      DOUBLE PRECISION, INTENT(INOUT) :: ALF 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: EFS 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
