      MODULE lsame_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  22:48:56  03/08/06  
      LOGICAL FUNCTION lsame (CA, CB) 
      character (LEN = 1), INTENT(IN) :: CA 
      character (LEN = 1), INTENT(IN) :: CB 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
