      MODULE makeuf_I   
      INTERFACE
      SUBROUTINE makeuf (U, UOLD, G, EIGS, LAST, NORBS, NCLOSE, DIFF, ATOL) 
      logical, INTENT(OUT) :: LAST 
      integer, INTENT(IN) :: NORBS 
      integer, INTENT(IN) :: NCLOSE 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(INOUT) :: U 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(INOUT) :: UOLD 
      DOUBLE PRECISION, DIMENSION(NORBS,NORBS), INTENT(IN) :: G 
      DOUBLE PRECISION, DIMENSION(NORBS), INTENT(IN) :: EIGS       
      DOUBLE PRECISION, INTENT(OUT) :: DIFF 
      DOUBLE PRECISION, INTENT(IN) :: ATOL 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
