      MODULE makopr_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:23  03/09/06  
      SUBROUTINE makopr (NUMAT, COORD, IERROR, R) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER :: NUMAT 
      REAL(DOUBLE), DIMENSION(*) :: COORD 
      INTEGER, INTENT(OUT) :: IERROR 
      REAL(DOUBLE), DIMENSION(3,3) :: R 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
