      MODULE maksym_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:24  03/09/06  
      subroutine maksym (loc, xparam, xstore)
      use molkst_C, only: nvar, ndep
    
     !.. Implicit Declarations ..
      implicit none
     !
     !.. Formal Arguments ..
      integer, dimension (2, nvar), intent (inout) :: loc
      double precision, dimension (nvar), intent (inout) :: xparam, xstore
     !
      end subroutine maksym
      END INTERFACE 
      END MODULE 
