      MODULE mamult_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  08:34:51  03/09/06  
      SUBROUTINE mamult (A, B, C, N, ONE) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: A 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: B 
      REAL(DOUBLE), DIMENSION(*), INTENT(INOUT) :: C 
      INTEGER, INTENT(IN) :: N 
      REAL(DOUBLE), INTENT(IN) :: ONE 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
