      MODULE mat33_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  09:18:42  03/09/06  
      SUBROUTINE mat33 (A, B, C) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(9), INTENT(IN) :: A 
      REAL(DOUBLE), DIMENSION(9), INTENT(IN) :: B 
      REAL(DOUBLE), DIMENSION(9), INTENT(OUT) :: C 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
