      MODULE mat33_I   
      INTERFACE
      SUBROUTINE mat33 (A, B, C) 
      DOUBLE PRECISION, DIMENSION(9), INTENT(IN) :: A 
      DOUBLE PRECISION, DIMENSION(9), INTENT(IN) :: B 
      DOUBLE PRECISION, DIMENSION(9), INTENT(OUT) :: C 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
