      MODULE matout_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:24  03/09/06  
      SUBROUTINE matout (A, B, NC, NR, NDIM) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: NC 
      INTEGER, INTENT(INOUT) :: NR 
      INTEGER, INTENT(IN) :: NDIM 
      REAL(DOUBLE), DIMENSION(NDIM,NDIM), INTENT(IN) :: A 
      REAL(DOUBLE), DIMENSION(NDIM), INTENT(IN) :: B       
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
