      MODULE matou1_I   
      INTERFACE
      SUBROUTINE matou1 (A, B, NCX, NR, NDIM, IFLAG) 
      INTEGER, INTENT(IN) :: NCX 
      INTEGER, INTENT(INOUT) :: NR 
      INTEGER, INTENT(IN) :: NDIM 
      INTEGER, INTENT(IN) :: IFLAG 
      DOUBLE PRECISION, DIMENSION(NR,NR), INTENT(IN) :: A 
      DOUBLE PRECISION, DIMENSION(NDIM), INTENT(IN) :: B       
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
