      MODULE matou1_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:24  03/09/06  
      SUBROUTINE matou1 (A, B, NCX, NR, NDIM, IFLAG) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: NCX 
      INTEGER, INTENT(INOUT) :: NR 
      INTEGER, INTENT(IN) :: NDIM 
      INTEGER, INTENT(IN) :: IFLAG 
      REAL(DOUBLE), DIMENSION(NR,NR), INTENT(IN) :: A 
      REAL(DOUBLE), DIMENSION(NDIM), INTENT(IN) :: B       
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
