      MODULE matout_I   
      INTERFACE
      SUBROUTINE matout (A, B, NC, NR, NDIM) 
      INTEGER, INTENT(IN) :: NC 
      INTEGER, INTENT(INOUT) :: NR 
      INTEGER, INTENT(IN) :: NDIM 
      DOUBLE PRECISION, DIMENSION(NDIM,NDIM), INTENT(IN) :: A 
      DOUBLE PRECISION, DIMENSION(NDIM), INTENT(IN) :: B       
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
