      MODULE mecip_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:25  03/09/06  
      SUBROUTINE mecip () 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
