      MODULE mecid_I   
      INTERFACE
      SUBROUTINE mecid (EIGS, GSE, EIGA, DIAG, XY) 
      use meci_C, only : nmos
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: EIGS 
      DOUBLE PRECISION, INTENT(OUT) :: GSE 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: EIGA 
      DOUBLE PRECISION, DIMENSION(*), INTENT(OUT) :: DIAG 
      DOUBLE PRECISION, DIMENSION(NMOS,NMOS,NMOS,NMOS), INTENT(IN) :: XY 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
