      MODULE mecid_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:24  03/09/06  
      SUBROUTINE mecid (EIGS, GSE, EIGA, DIAG, XY) 
      USE vast_kind_param,ONLY: DOUBLE 
      use meci_C, only : nmos
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: EIGS 
      REAL(DOUBLE), INTENT(OUT) :: GSE 
      REAL(DOUBLE), DIMENSION(*), INTENT(INOUT) :: EIGA 
      REAL(DOUBLE), DIMENSION(*), INTENT(OUT) :: DIAG 
      REAL(DOUBLE), DIMENSION(NMOS,NMOS,NMOS,NMOS), INTENT(IN) :: XY 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
