      MODULE meci_I  
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  16:24:08  03/14/06  
      REAL(KIND(0.0D0)) FUNCTION meci()
      END FUNCTION  
      END INTERFACE 
      END MODULE 
