      MODULE mepchg_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:59:30  03/10/06  
      SUBROUTINE mepchg (CO, POTPT, NMEP) 
      USE vast_kind_param,ONLY: DOUBLE 
      real(DOUBLE), DIMENSION(3,*), INTENT(IN) :: CO 
      real(DOUBLE), DIMENSION(3,*), INTENT(IN) :: POTPT 
      integer, INTENT(IN) :: NMEP      
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
