      MODULE mepmap_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:33  03/09/06  
      SUBROUTINE mepmap (C1) 
      USE vast_kind_param,ONLY: DOUBLE 
      real(DOUBLE), DIMENSION(3,*), INTENT(IN) :: C1 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
