      MODULE meprot_I   
      INTERFACE
      SUBROUTINE meprot (C, R0, T, XM, YM, ICASE, STEP, C1, Z0, IBACK) 
      DOUBLE PRECISION, DIMENSION(3,*), INTENT(IN) :: C 
      DOUBLE PRECISION, DIMENSION(3), INTENT(INOUT) :: R0 
      DOUBLE PRECISION, DIMENSION(3,3), INTENT(INOUT) :: T 
      DOUBLE PRECISION, INTENT(OUT) :: XM 
      DOUBLE PRECISION, INTENT(OUT) :: YM 
      integer, INTENT(IN) :: ICASE 
      DOUBLE PRECISION, INTENT(IN) :: STEP 
      DOUBLE PRECISION, DIMENSION(3,*), INTENT(OUT) :: C1 
      DOUBLE PRECISION, INTENT(IN) :: Z0 
      integer, INTENT(OUT) :: IBACK 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
