      MODULE minv_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:25  03/09/06  
      SUBROUTINE minv (A, N, D) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(*), INTENT(INOUT) :: A 
      INTEGER, INTENT(IN) :: N 
      REAL(DOUBLE), INTENT(OUT) :: D 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
