      MODULE mpcbds_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  08:35:05  03/09/06  
      SUBROUTINE mpcbds (BONDAB) 
      USE vast_kind_param,ONLY: DOUBLE 
      use molkst_C, only : NUMAT 
      REAL(DOUBLE), DIMENSION((NUMAT*(NUMAT + 1))/2), INTENT(IN) :: BONDAB       
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
