      MODULE mpcpop_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:29  03/09/06  
      SUBROUTINE mpcpop (ICOK) 
      integer, intent(in) :: icok
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
