      MODULE mtxmc_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  08:27:20  03/09/06  
      SUBROUTINE mtxmc (A, NAR, B, NBR, C) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: NAR, NBR
      REAL(DOUBLE), DIMENSION(NBR,NAR) :: A       
      REAL(DOUBLE), DIMENSION(NBR,NAR) :: B 
      REAL(DOUBLE), DIMENSION(*) :: C 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
