      MODULE mult33_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  08:35:23  03/09/06  
      SUBROUTINE mult33 (FMAT, IPLACE) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(3,3), INTENT(IN) :: FMAT 
      INTEGER, INTENT(IN) :: IPLACE 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
