      MODULE mult33_I   
      INTERFACE
      SUBROUTINE mult33 (FMAT, IPLACE) 
      DOUBLE PRECISION, DIMENSION(3,3), INTENT(IN) :: FMAT 
      INTEGER, INTENT(IN) :: IPLACE 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
