      MODULE mult_I   
      INTERFACE
      SUBROUTINE mult (C, S, VECS, N) 
      INTEGER, INTENT(IN) :: N  
      DOUBLE PRECISION, DIMENSION(N,*), INTENT(IN) :: C 
      DOUBLE PRECISION, DIMENSION(N,*), INTENT(IN) :: S 
      DOUBLE PRECISION, DIMENSION(N,*), INTENT(OUT) :: VECS       
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
