      MODULE mult_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  08:35:11  03/09/06  
      SUBROUTINE mult (C, S, VECS, N) 
      USE vast_kind_param,ONLY: DOUBLE
      INTEGER, INTENT(IN) :: N  
      REAL(DOUBLE), DIMENSION(N,*), INTENT(IN) :: C 
      REAL(DOUBLE), DIMENSION(N,*), INTENT(IN) :: S 
      REAL(DOUBLE), DIMENSION(N,*), INTENT(OUT) :: VECS       
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
