      MODULE mxm_I   
      INTERFACE
      SUBROUTINE mxm (A, NAR, B, NBR, C, NCC) 
      INTEGER, INTENT(IN) :: NAR, NBR, NCC
      DOUBLE PRECISION, DIMENSION(NAR,NBR) :: A       
      DOUBLE PRECISION, DIMENSION(NBR,NCC) :: B 
      DOUBLE PRECISION, DIMENSION(NAR,NCC) :: C 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

