      MODULE mxmt_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  08:27:30  03/09/06  
      SUBROUTINE mxmt (A, NAR, B, NBR, C, NCC) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: NAR, NBR, NCC
      REAL(DOUBLE), DIMENSION(NAR,NBR) :: A       
      REAL(DOUBLE), DIMENSION(NCC,NBR) :: B 
      REAL(DOUBLE), DIMENSION(NAR,NCC) :: C 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
