      MODULE mxv_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  22:40:54  03/08/06  
      SUBROUTINE mxv (a, nar, vecx, nbr, vecy)  
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: NAR, NBR
      REAL(DOUBLE), DIMENSION(NAR,NBR) :: A       
      REAL(DOUBLE), DIMENSION(NBR) :: vecx 
      REAL(DOUBLE), DIMENSION(NAR) :: vecy 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE

