      MODULE myword_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  08:35:31  03/09/06  
      LOGICAL FUNCTION myword (KEYWRD, TESTWD) 
      CHARACTER (LEN = *), INTENT(INOUT) :: KEYWRD 
      CHARACTER (LEN = *), INTENT(IN) :: TESTWD 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
