      MODULE nllsq_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:30  03/09/06  
      SUBROUTINE nllsq () 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
