      MODULE nllsn_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:30  03/09/06  
      SUBROUTINE nllsn (X, N, ESCF, Q, R, P9, PA, PB) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: N 
      real(DOUBLE), DIMENSION(N), INTENT(INOUT) :: X       
      real(DOUBLE), INTENT(IN) :: ESCF 
      real(DOUBLE), DIMENSION(N,N), INTENT(INOUT) :: Q 
      real(DOUBLE), DIMENSION(N + 2,N + 2), INTENT(INOUT) :: R 
      real(DOUBLE) :: P9 
      real(DOUBLE) :: PA 
      real(DOUBLE) :: PB 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
