      MODULE nllsn_I   
      INTERFACE
      SUBROUTINE nllsn (X, N, ESCF, Q, R, P9, PA, PB) 
      integer, INTENT(IN) :: N 
      DOUBLE PRECISION, DIMENSION(N), INTENT(INOUT) :: X       
      DOUBLE PRECISION, INTENT(IN) :: ESCF 
      DOUBLE PRECISION, DIMENSION(N,N), INTENT(INOUT) :: Q 
      DOUBLE PRECISION, DIMENSION(N + 2,N + 2), INTENT(INOUT) :: R 
      DOUBLE PRECISION :: P9 
      DOUBLE PRECISION :: PA 
      DOUBLE PRECISION :: PB 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
