      MODULE nonope_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  21:23:38  03/14/06  
      SUBROUTINE nonope (U0X, U1Y, U1Z, U1X, U0Y, U0Z, G0X, G1Y, G1Z, G1X, G0Y&
        , G0Z) 
      USE vast_kind_param,ONLY: DOUBLE  
      use molkst_C, only : norbs
      real(DOUBLE), DIMENSION(norbs,norbs) :: U0X 
      real(DOUBLE), DIMENSION(norbs,norbs) :: U1Y 
      real(DOUBLE), DIMENSION(norbs,norbs) :: U1Z 
      real(DOUBLE), DIMENSION(norbs,norbs) :: U1X 
      real(DOUBLE), DIMENSION(norbs,norbs) :: U0Y 
      real(DOUBLE), DIMENSION(norbs,norbs) :: U0Z 
      real(DOUBLE), DIMENSION(norbs,norbs) :: G0X 
      real(DOUBLE), DIMENSION(norbs,norbs) :: G1Y 
      real(DOUBLE), DIMENSION(norbs,norbs) :: G1Z 
      real(DOUBLE), DIMENSION(norbs,norbs) :: G1X 
      real(DOUBLE), DIMENSION(norbs,norbs) :: G0Y 
      real(DOUBLE), DIMENSION(norbs,norbs) :: G0Z 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
