      MODULE nuchar_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:31  03/09/06  
      SUBROUTINE nuchar (LINE, L_LINE, VALUE, NVALUE) 
      USE vast_kind_param,ONLY: DOUBLE 
      CHARACTER, INTENT(INOUT) :: LINE*(*)
      integer, intent(in) :: L_Line
      REAL(DOUBLE), DIMENSION(40), INTENT(OUT) :: VALUE 
      INTEGER, INTENT(OUT) :: NVALUE 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
