      MODULE orient_I   
      INTERFACE
      SUBROUTINE orient (NUMAT, COORD, R) 
      INTEGER :: NUMAT 
      DOUBLE PRECISION, DIMENSION(3,NUMAT) :: COORD 
      DOUBLE PRECISION, DIMENSION(3,3) :: R 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
