      MODULE orient_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:31  03/09/06  
      SUBROUTINE orient (NUMAT, COORD, R) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER :: NUMAT 
      REAL(DOUBLE), DIMENSION(3,NUMAT) :: COORD 
      REAL(DOUBLE), DIMENSION(3,3) :: R 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
