      MODULE packp_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:33  03/09/06  
      SUBROUTINE packp (P, PP, MN) 
      USE vast_kind_param,ONLY: DOUBLE 
      real(DOUBLE), DIMENSION(*), INTENT(IN) :: P 
      real(DOUBLE), DIMENSION(*), INTENT(OUT) :: PP 
      integer, INTENT(OUT) :: MN 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
