      MODULE parsav_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  12:17:05  03/10/06  
      SUBROUTINE parsav (MODE, N, M, Q, R, efslst, xlast, iiium) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: MODE 
      INTEGER, INTENT(IN) :: N 
      INTEGER, INTENT(IN) :: M 
      REAL(DOUBLE), DIMENSION(N,N), INTENT(IN) :: Q 
      REAL(DOUBLE), DIMENSION(N + 2,N + 2), INTENT(IN) :: R
      integer, dimension(6) :: iiium
      real(double), dimension(n) :: efslst, xlast
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
