      MODULE partxy_I   
      INTERFACE
      SUBROUTINE partxy (C34, PQ34, W) 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: C34 
      DOUBLE PRECISION, DIMENSION(*), INTENT(INOUT) :: PQ34 
      DOUBLE PRECISION, DIMENSION(*) :: W 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
