      MODULE pathk_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:32  03/09/06  
      SUBROUTINE pathk () 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
