      MODULE pmepco_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:33  03/09/06  
      SUBROUTINE pmepco (PP, RIA, W, UI, CO, NONZO, ID) 
      USE vast_kind_param,ONLY: DOUBLE 
      real(DOUBLE), DIMENSION(*), INTENT(IN) :: PP 
      real(DOUBLE), DIMENSION(*), INTENT(IN) :: RIA 
      real(DOUBLE), DIMENSION(3), INTENT(IN) :: W 
      real(DOUBLE), INTENT(OUT) :: UI 
      real(DOUBLE), DIMENSION(3,*), INTENT(IN) :: CO 
      integer, INTENT(IN) :: NONZO 
      integer, INTENT(IN) :: ID 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
