      MODULE pmepco_I   
      INTERFACE
      SUBROUTINE pmepco (PP, RIA, W, UI, CO, NONZO, ID) 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: PP 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: RIA 
      DOUBLE PRECISION, DIMENSION(3), INTENT(IN) :: W 
      DOUBLE PRECISION, INTENT(OUT) :: UI 
      DOUBLE PRECISION, DIMENSION(3,*), INTENT(IN) :: CO 
      integer, INTENT(IN) :: NONZO 
      integer, INTENT(IN) :: ID 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
