      MODULE poij_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  12:41:19  03/10/06  
      REAL(KIND(0.0D0)) FUNCTION poij (L, D, FG) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: L 
      real(DOUBLE), INTENT(IN) :: D 
      real(DOUBLE), INTENT(IN) :: FG 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
