      MODULE polar_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  21:23:38  03/14/06  
      SUBROUTINE polar () 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
