      MODULE powsav_I   
      INTERFACE
      SUBROUTINE powsav (HESS, GRAD, XPARAM, PMAT, ILOOP, BMAT, IPOW) 
      use molkst_C, only : nvar
      DOUBLE PRECISION, DIMENSION(NVAR,NVAR), INTENT(IN) :: HESS 
      DOUBLE PRECISION, DIMENSION(NVAR), INTENT(IN) :: GRAD 
      DOUBLE PRECISION, DIMENSION(NVAR), INTENT(IN) :: XPARAM 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: PMAT 
      INTEGER, INTENT(INOUT) :: ILOOP 
      DOUBLE PRECISION, DIMENSION(NVAR,NVAR), INTENT(IN) :: BMAT 
      INTEGER, DIMENSION(9), INTENT(IN) :: IPOW 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
