      MODULE powsq_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:35  03/09/06  
      SUBROUTINE powsq () 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
