      MODULE printp_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  12:41:19  03/10/06  
      SUBROUTINE printp (I, PARA, VALUE, TXT) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: I 
      character (LEN = *), INTENT(IN) :: PARA 
      real(DOUBLE), INTENT(IN) :: VALUE 
      character (LEN = *), INTENT(IN) :: TXT 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
