      MODULE prthes_I   
      INTERFACE
      SUBROUTINE prthes (EIGVAL, NVAR, HESS, U) 
      integer, INTENT(IN) :: NVAR
      DOUBLE PRECISION, DIMENSION(nvar), INTENT(IN) :: EIGVAL        
      DOUBLE PRECISION, DIMENSION(NVAR,NVAR), INTENT(IN) :: HESS 
      DOUBLE PRECISION, DIMENSION(NVAR,NVAR), INTENT(IN) :: U 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
