      MODULE prttim_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  08:35:39  03/09/06  
      SUBROUTINE prttim (TLEFT, TPRT, TXT) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), INTENT(IN) :: TLEFT 
      REAL(DOUBLE), INTENT(OUT) :: TPRT 
      CHARACTER (LEN = 1), INTENT(OUT) :: TXT 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
