
      MODULE pulay_for_gpu_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:04:13  03/09/06  
      SUBROUTINE pulay_for_gpu (F, P, N, FPPF, FOCK, EMAT, LFOCK, NFOCK, MSIZE, START &
       & , PL) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(*), INTENT(INOUT) :: F 
      REAL(DOUBLE), DIMENSION(*) :: P 
      INTEGER, INTENT(IN) :: N 
      REAL(DOUBLE), DIMENSION(*) :: FPPF 
      REAL(DOUBLE), DIMENSION(*), INTENT(INOUT) :: FOCK 
      REAL(DOUBLE), DIMENSION(20,20), INTENT(INOUT) :: EMAT 
      INTEGER, INTENT(INOUT) :: LFOCK 
      INTEGER, INTENT(INOUT) :: NFOCK 
      INTEGER, INTENT(IN) :: MSIZE 
      LOGICAL, INTENT(INOUT) :: START 
      REAL(DOUBLE), INTENT(OUT) :: PL 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 

