      MODULE quadr_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  08:35:46  03/09/06  
      SUBROUTINE quadr (F0, F1, F2, X1, X2, A, B, C) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), INTENT(IN) :: F0 
      REAL(DOUBLE), INTENT(IN) :: F1 
      REAL(DOUBLE), INTENT(IN) :: F2 
      REAL(DOUBLE), INTENT(IN) :: X1 
      REAL(DOUBLE), INTENT(IN) :: X2 
      REAL(DOUBLE), INTENT(OUT) :: A 
      REAL(DOUBLE), INTENT(OUT) :: B 
      REAL(DOUBLE), INTENT(OUT) :: C 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
