      MODULE react1_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:04:13  03/09/06  
      SUBROUTINE react1 () 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
