      MODULE reada_I   
      INTERFACE
      DOUBLE PRECISION FUNCTION reada (STRING, ISTART) 
      CHARACTER (LEN = *), INTENT(IN) :: STRING 
      INTEGER, INTENT(IN) :: ISTART 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
