      MODULE redatm_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:12  03/09/06  
      LOGICAL FUNCTION redatm (IRED, A, B, C) 
      INTEGER :: IRED 
      INTEGER :: A 
      INTEGER :: B 
      INTEGER :: C 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
