      MODULE repp_I   
      INTERFACE
      SUBROUTINE repp (NI, NJ, RIJ, RI, CORE, CUTOFF, A0, EV, EV1, EV2, EV3&
        , EV4) 
      INTEGER, INTENT(IN) :: NI 
      INTEGER, INTENT(IN) :: NJ 
      DOUBLE PRECISION, INTENT(IN) :: RIJ 
      DOUBLE PRECISION, DIMENSION(22), INTENT(OUT) :: RI 
      DOUBLE PRECISION, DIMENSION(4,2), INTENT(OUT) :: CORE 
      DOUBLE PRECISION, INTENT(IN) :: CUTOFF 
      DOUBLE PRECISION, INTENT(IN) :: A0 
      DOUBLE PRECISION, INTENT(IN) :: EV 
      DOUBLE PRECISION, INTENT(IN) :: EV1 
      DOUBLE PRECISION, INTENT(IN) :: EV2 
      DOUBLE PRECISION, INTENT(IN) :: EV3 
      DOUBLE PRECISION, INTENT(IN) :: EV4 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
