      MODULE repp_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:05:00  03/09/06  
      SUBROUTINE repp (NI, NJ, RIJ, RI, CORE, CUTOFF, A0, EV, EV1, EV2, EV3&
        , EV4) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: NI 
      INTEGER, INTENT(IN) :: NJ 
      REAL(DOUBLE), INTENT(IN) :: RIJ 
      REAL(DOUBLE), DIMENSION(22), INTENT(OUT) :: RI 
      REAL(DOUBLE), DIMENSION(4,2), INTENT(OUT) :: CORE 
      REAL(DOUBLE), INTENT(IN) :: CUTOFF 
      REAL(DOUBLE), INTENT(IN) :: A0 
      REAL(DOUBLE), INTENT(IN) :: EV 
      REAL(DOUBLE), INTENT(IN) :: EV1 
      REAL(DOUBLE), INTENT(IN) :: EV2 
      REAL(DOUBLE), INTENT(IN) :: EV3 
      REAL(DOUBLE), INTENT(IN) :: EV4 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
