      MODULE resolv_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:05:01  03/09/06  
      SUBROUTINE resolv (C, COLD, MDIM, EIG, NOCC) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: MDIM, NOCC
      REAL(DOUBLE), DIMENSION(MDIM,MDIM), INTENT(INOUT) :: C 
      REAL(DOUBLE), DIMENSION(MDIM,MDIM), INTENT(IN) :: COLD      
      REAL(DOUBLE), DIMENSION(NOCC), INTENT(IN) :: EIG 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
