      MODULE rijkl_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  12:41:19  03/10/06  
      REAL(KIND(0.0D0)) FUNCTION rijkl (NI, NJ, IJ, KL, LI, LJ, LK, LL, IC, R) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: NI 
      integer, INTENT(IN) :: NJ 
      integer, INTENT(IN) :: IJ 
      integer, INTENT(IN) :: KL 
      integer, INTENT(IN) :: LI 
      integer, INTENT(IN) :: LJ 
      integer, INTENT(IN) :: LK 
      integer, INTENT(IN) :: LL 
      integer, INTENT(IN) :: IC 
      real(DOUBLE) :: R 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
