      MODULE rotate_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:05:01  03/09/06  
      SUBROUTINE rotate (NI, NJ, XI, XJ, W, KR, E1B, E2A, ENUC) 
      USE vast_kind_param,ONLY: DOUBLE  
      INTEGER, INTENT(IN) :: NI 
      INTEGER, INTENT(IN) :: NJ 
      REAL(DOUBLE), DIMENSION(3), INTENT(IN) :: XI 
      REAL(DOUBLE), DIMENSION(3), INTENT(IN) :: XJ 
      REAL(DOUBLE), DIMENSION(*), INTENT(OUT) :: W 
      INTEGER, INTENT(INOUT) :: KR 
      REAL(DOUBLE), DIMENSION(45), INTENT(OUT) :: E1B 
      REAL(DOUBLE), DIMENSION(45), INTENT(OUT) :: E2A 
      REAL(DOUBLE), INTENT(OUT) :: ENUC 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
