      MODULE rotatd_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  12:41:19  03/10/06  
      SUBROUTINE rotatd (NI, NJ, CI, CJ, W, KR, ENUC) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, intent(in) :: NI, NJ 
!GBR
      integer :: kr      
      real(DOUBLE) :: CI(3) 
      real(DOUBLE) :: CJ(3)
      real(DOUBLE), dimension(*) :: W 
      integer :: LMW 
      real(DOUBLE) :: ENUC 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
