      MODULE rotat_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:46:59  03/09/06  
      SUBROUTINE rotat (COORD, I, J, IX, RIJ, DEL1, IDX) 
      USE vast_kind_param,ONLY: DOUBLE 
      real(DOUBLE), DIMENSION(3,25), INTENT(IN) :: COORD 
      integer, INTENT(IN) :: I 
      integer, INTENT(IN) :: J 
      integer, INTENT(IN) :: IX 
      real(DOUBLE), INTENT(IN) :: RIJ 
      real(DOUBLE), INTENT(IN) :: DEL1 
      integer, INTENT(IN) :: IDX 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
