      MODULE rotmat_I   
      INTERFACE
      SUBROUTINE rotmat (NJ, NI, COORDI, COORDJ, R) 
      integer, INTENT(IN) :: NJ 
      integer, INTENT(IN) :: NI 
      DOUBLE PRECISION, DIMENSION(3), INTENT(IN) :: COORDI 
      DOUBLE PRECISION, DIMENSION(3), INTENT(IN) :: COORDJ 
      DOUBLE PRECISION, INTENT(OUT) :: R 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
