      MODULE rotmat_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  12:41:19  03/10/06  
      SUBROUTINE rotmat (NJ, NI, COORDI, COORDJ, R) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: NJ 
      integer, INTENT(IN) :: NI 
      real(DOUBLE), DIMENSION(3), INTENT(IN) :: COORDI 
      real(DOUBLE), DIMENSION(3), INTENT(IN) :: COORDJ 
      real(DOUBLE), INTENT(OUT) :: R 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
