      MODULE rotmol_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  08:15:45  03/09/06  
      SUBROUTINE rotmol (NUMAT, COORD, SINA, COSA, I, J, R) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER :: NUMAT 
      REAL(DOUBLE), DIMENSION(3,NUMAT) :: COORD 
      REAL(DOUBLE), INTENT(IN) :: SINA 
      REAL(DOUBLE), INTENT(IN) :: COSA 
      INTEGER, INTENT(IN) :: I 
      INTEGER, INTENT(IN) :: J 
      REAL(DOUBLE), DIMENSION(3,3), INTENT(INOUT) :: R 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
