      MODULE rsc_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  12:41:19  03/10/06  
      REAL(KIND(0.0D0)) FUNCTION rsc (K, NA, EA, NB, EB, NC, EC, ND, ED) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: K 
      integer, INTENT(IN) :: NA 
      real(DOUBLE), INTENT(IN) :: EA 
      integer, INTENT(IN) :: NB 
      real(DOUBLE), INTENT(IN) :: EB 
      integer, INTENT(IN) :: NC 
      real(DOUBLE), INTENT(IN) :: EC 
      integer, INTENT(IN) :: ND 
      real(DOUBLE), INTENT(IN) :: ED 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
