      MODULE schmib_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:05:01  03/09/06  
      SUBROUTINE schmib (U, N, NDIM) 
      USE vast_kind_param,ONLY: DOUBLE       
      INTEGER, INTENT(IN) :: N 
      INTEGER, INTENT(IN) :: NDIM 
      REAL(DOUBLE), DIMENSION(NDIM,NDIM), INTENT(INOUT) :: U 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
