      MODULE scprm_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  12:41:19  03/10/06  
      SUBROUTINE scprm (NI, R066, R266, R466, R016, R244, R036, R236, R155&
        , R355, R125, R234, R246) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: NI 
      real(DOUBLE), INTENT(OUT) :: R066, r266, r466, r016, r244, r036, r236, &
      r155, r355, r125, r234, r246
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
