      MODULE search_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:05:02  03/09/06  
      subroutine search(xparam, alpha, sig, nvar, gmin, funct, amin, anext ) 
      USE vast_kind_param, ONLY:  double 
      integer  :: nvar 
      real(double) , intent(inout) :: alpha 
      real(double) , intent(inout) :: gmin 
      real(double)  :: funct, amin, anext
      real(double)  :: xparam(*) 
      real(double) , intent(in) :: sig(*) 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
