      MODULE second2_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  08:48:05  03/09/06  
      REAL(KIND(0.0D0)) FUNCTION second2 (MODE) 
      INTEGER, INTENT(IN) :: MODE 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
