      MODULE set_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  08:35:52  03/09/06  
      SUBROUTINE set (S1, S2, NA, NB, RAB, II) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), INTENT(IN) :: S1 
      REAL(DOUBLE), INTENT(IN) :: S2 
      INTEGER, INTENT(IN) :: NA 
      INTEGER, INTENT(IN) :: NB 
      REAL(DOUBLE), INTENT(IN) :: RAB 
      INTEGER, INTENT(IN) :: II 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
