      MODULE solrot_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:04:15  03/09/06  
      SUBROUTINE solrot (NI, NJ, XI, XJ, WJ, WK, KR, E1B, E2A, ENUC) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: NI 
      INTEGER, INTENT(IN) :: NJ 
      REAL(DOUBLE), DIMENSION(3), INTENT(IN) :: XI 
      REAL(DOUBLE), DIMENSION(3), INTENT(IN) :: XJ 
      REAL(DOUBLE), DIMENSION(2025), INTENT(OUT) :: WJ, wk
      INTEGER, INTENT(INOUT) :: KR 
      REAL(DOUBLE), DIMENSION(45), INTENT(INOUT) :: E1B 
      REAL(DOUBLE), DIMENSION(45), INTENT(INOUT) :: E2A 
      REAL(DOUBLE), INTENT(OUT) :: ENUC 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
