      MODULE sort_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  08:27:36  03/09/06  
      SUBROUTINE sort (VAL, VEC, N) 
      INTEGER, INTENT(IN) :: N 
      REAL, DIMENSION(*), INTENT(INOUT) :: VAL 
      COMPLEX, DIMENSION(N,*), INTENT(INOUT) :: VEC       
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
