      MODULE ss_I   
      INTERFACE
      DOUBLE PRECISION FUNCTION ss (NA, NB, LA1, LB1, M1, UA, UB, R1, A0) 
      INTEGER, INTENT(IN) :: NA 
      INTEGER, INTENT(IN) :: NB 
      INTEGER, INTENT(IN) :: LA1 
      INTEGER, INTENT(IN) :: LB1 
      INTEGER, INTENT(IN) :: M1 
      DOUBLE PRECISION, INTENT(IN) :: UA 
      DOUBLE PRECISION, INTENT(IN) :: UB 
      DOUBLE PRECISION, INTENT(IN) :: R1 
      DOUBLE PRECISION, INTENT(IN) :: A0 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
