      MODULE ss_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:04:15  03/09/06  
      REAL(KIND(0.0D0)) FUNCTION ss (NA, NB, LA1, LB1, M1, UA, UB, R1, A0) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: NA 
      INTEGER, INTENT(IN) :: NB 
      INTEGER, INTENT(IN) :: LA1 
      INTEGER, INTENT(IN) :: LB1 
      INTEGER, INTENT(IN) :: M1 
      REAL(DOUBLE), INTENT(IN) :: UA 
      REAL(DOUBLE), INTENT(IN) :: UB 
      REAL(DOUBLE), INTENT(IN) :: R1 
      REAL(DOUBLE), INTENT(IN) :: A0 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
