      MODULE suma2_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:18  03/09/06  
      SUBROUTINE suma2 (P, EP) 
      USE vast_kind_param,ONLY: DOUBLE 
      real(DOUBLE), DIMENSION(*), INTENT(IN) :: P 
      real(DOUBLE), INTENT(IN) :: EP 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
