      MODULE supdot_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  08:27:50  03/09/06  
      SUBROUTINE supdot (S, H, G, N) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(*), INTENT(INOUT) :: S 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: H 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: G 
      INTEGER, INTENT(IN) :: N 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
