      MODULE superd_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:04:15  03/09/06  
      SUBROUTINE superd (C, EIGS, NORBS, NELECS, NUMAT, NAT) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: NORBS 
      INTEGER, INTENT(IN) :: NELECS 
      INTEGER, INTENT(IN) :: NUMAT
      REAL(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(IN) :: C 
      REAL(DOUBLE), DIMENSION(NORBS), INTENT(IN) :: EIGS        
      INTEGER, DIMENSION(NUMAT), INTENT(IN) :: NAT 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
