      MODULE surfa_I   
      INTERFACE
      SUBROUTINE surfa (CO, POTPT, NMEP) 
      DOUBLE PRECISION, DIMENSION(3,*), INTENT(IN) :: CO 
      DOUBLE PRECISION, DIMENSION(3,*), INTENT(OUT) :: POTPT 
      integer, INTENT(INOUT) :: NMEP 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
