      MODULE swap_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:05:03  03/09/06  
      SUBROUTINE swap (C, N, MDIM, NOCC, IFILL) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: N 
      INTEGER, INTENT(IN) :: MDIM 
      INTEGER, INTENT(IN) :: NOCC 
      INTEGER, INTENT(INOUT) :: IFILL
      REAL(DOUBLE), DIMENSION(MDIM,MDIM), INTENT(INOUT) :: C 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
