      MODULE symdec_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  12:50:03  03/10/06  
      LOGICAL FUNCTION symdec (N1, IELEM) 
      INTEGER, INTENT(IN) :: N1 
      INTEGER, DIMENSION(20), INTENT(IN) :: IELEM 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
