      MODULE symh_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  09:16:02  03/09/06  
      SUBROUTINE symh (H, DIP, I, N, IPO) 
      USE vast_kind_param,ONLY: DOUBLE
      USE molkst_C, only : numat 
      REAL(DOUBLE), DIMENSION(*), INTENT(INOUT) :: H 
      REAL(DOUBLE), DIMENSION(3,*), INTENT(INOUT) :: DIP 
      integer, dimension (numat, 120), intent (in) :: ipo
      INTEGER, INTENT(IN) :: I 
      INTEGER, INTENT(IN) :: N 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
