      MODULE symopr_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  08:18:55  03/09/06  
      SUBROUTINE symopr (NUMAT, COORD, JUMP, R) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: NUMAT 
      REAL(DOUBLE), DIMENSION(3,NUMAT), INTENT(INOUT) :: COORD 
      INTEGER, INTENT(IN) :: JUMP 
      REAL(DOUBLE), DIMENSION(3,3), INTENT(IN) :: R 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
