      MODULE symoir_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:05:03  03/09/06  
      SUBROUTINE symoir (ITYPE, VECTS, EIGS, NVECS, R, IMAT) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: ITYPE 
      INTEGER, INTENT(IN) :: NVECS, IMAT
      REAL(DOUBLE), DIMENSION(NVECS,*) :: VECTS 
      REAL(DOUBLE), DIMENSION(*), INTENT(IN) :: EIGS       
      REAL(DOUBLE), DIMENSION(3,3) :: R 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
