      MODULE symoir_I   
      INTERFACE
      SUBROUTINE symoir (ITYPE, VECTS, EIGS, NVECS, R, IMAT) 
      INTEGER, INTENT(IN) :: ITYPE 
      INTEGER, INTENT(IN) :: NVECS, IMAT
      DOUBLE PRECISION, DIMENSION(NVECS,*) :: VECTS 
      DOUBLE PRECISION, DIMENSION(*), INTENT(IN) :: EIGS       
      DOUBLE PRECISION, DIMENSION(3,3) :: R 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
