      MODULE symp_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  15:34:19  03/09/06  
      SUBROUTINE symp 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
