      MODULE sympop_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  08:35:59  03/09/06  
      SUBROUTINE sympop (H, I, ISKIP, DELDIP) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(*) :: H 
      INTEGER, INTENT(IN) :: I 
      INTEGER, INTENT(OUT) :: ISKIP 
      REAL(DOUBLE), DIMENSION(3,*) :: DELDIP 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
