      MODULE symr_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:05:03  03/09/06  
      SUBROUTINE symr 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
