      MODULE symtry_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:05:04  03/09/06  
      SUBROUTINE symtry 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
