      MODULE symtrz_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  15:19:33  03/09/06  
      SUBROUTINE symtrz (VECTS, EIGS, ITYPE, GETEIG) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(*) :: VECTS 
      REAL(DOUBLE), DIMENSION(*) :: EIGS 
      INTEGER, INTENT(IN) :: ITYPE 
      LOGICAL, INTENT(IN) :: GETEIG 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
