      MODULE symtrz_I   
      INTERFACE
      SUBROUTINE symtrz (VECTS, EIGS, ITYPE, GETEIG) 
      DOUBLE PRECISION, DIMENSION(*) :: VECTS 
      DOUBLE PRECISION, DIMENSION(*) :: EIGS 
      INTEGER, INTENT(IN) :: ITYPE 
      LOGICAL, INTENT(IN) :: GETEIG 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
