      MODULE tf_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  21:23:38  03/14/06  
      SUBROUTINE tf (UA, GA, UB, GB, T, NORBS) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: NORBS 
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(IN) :: UA 
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(IN) :: GA 
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(IN) :: UB 
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(IN) :: GB 
      real(DOUBLE), DIMENSION(NORBS,NORBS), INTENT(OUT) :: T    
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
