      MODULE thermo_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:04:16  03/09/06  
      SUBROUTINE thermo (A, B, C, LINEAR, SYM, VIBS, NVIBS, ESCF) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), INTENT(IN) :: A 
      REAL(DOUBLE), INTENT(IN) :: B 
      REAL(DOUBLE), INTENT(IN) :: C 
      LOGICAL, INTENT(IN) :: LINEAR 
      REAL(DOUBLE), INTENT(IN) :: SYM 
      REAL(DOUBLE), DIMENSION(*), INTENT(inout) :: VIBS 
      INTEGER, INTENT(IN) :: NVIBS 
      REAL(DOUBLE), INTENT(IN) :: ESCF 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
