      MODULE thermo_I   
      INTERFACE
      SUBROUTINE thermo (A, B, C, LINEAR, SYM, VIBS, NVIBS, ESCF) 
      DOUBLE PRECISION, INTENT(IN) :: A 
      DOUBLE PRECISION, INTENT(IN) :: B 
      DOUBLE PRECISION, INTENT(IN) :: C 
      LOGICAL, INTENT(IN) :: LINEAR 
      DOUBLE PRECISION, INTENT(IN) :: SYM 
      DOUBLE PRECISION, DIMENSION(*), INTENT(inout) :: VIBS 
      INTEGER, INTENT(IN) :: NVIBS 
      DOUBLE PRECISION, INTENT(IN) :: ESCF 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
