      MODULE time_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:16  03/09/06  
      INTEGER FUNCTION time ( ) 
      END FUNCTION  
      END INTERFACE 
      END MODULE 
