      MODULE timer_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  08:36:05  03/09/06  
      SUBROUTINE timer (A) 
      CHARACTER (LEN = *), INTENT(IN) :: A 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
