      MODULE transf_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  21:23:38  03/14/06  
      SUBROUTINE transf (F, G, C, NORB) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: NORB 
      real(DOUBLE), DIMENSION(NORB,NORB), INTENT(IN) :: F 
      real(DOUBLE), DIMENSION(NORB,NORB), INTENT(OUT) :: G 
      real(DOUBLE), DIMENSION(NORB,NORB), INTENT(IN) :: C       
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
