      MODULE trudgu_I   
      INTERFACE
      DOUBLE PRECISION FUNCTION trudgu (UL, X, UR, L1, LM, NDIM) 
      integer, INTENT(IN) :: L1 
      integer, INTENT(IN) :: LM 
      integer, INTENT(IN) :: NDIM 
      DOUBLE PRECISION, DIMENSION(NDIM,NDIM), INTENT(IN) :: UL 
      DOUBLE PRECISION, DIMENSION(NDIM,NDIM), INTENT(IN) :: X 
      DOUBLE PRECISION, DIMENSION(NDIM,NDIM), INTENT(IN) :: UR       
      END FUNCTION  
      END INTERFACE 
      END MODULE 
