      MODULE trudgu_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  21:23:38  03/14/06  
      REAL(KIND(0.0D0)) FUNCTION trudgu (UL, X, UR, L1, LM, NDIM) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: L1 
      integer, INTENT(IN) :: LM 
      integer, INTENT(IN) :: NDIM 
      real(DOUBLE), DIMENSION(NDIM,NDIM), INTENT(IN) :: UL 
      real(DOUBLE), DIMENSION(NDIM,NDIM), INTENT(IN) :: X 
      real(DOUBLE), DIMENSION(NDIM,NDIM), INTENT(IN) :: UR       
      END FUNCTION  
      END INTERFACE 
      END MODULE 
