      MODULE tx_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  12:41:19  03/10/06  
      SUBROUTINE tx (II, KK, REP, LOGV, V) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(IN) :: II 
      integer, INTENT(IN) :: KK 
      real(DOUBLE), DIMENSION(491), INTENT(IN) :: REP 
      logical, DIMENSION(45,45), INTENT(OUT) :: LOGV 
      real(DOUBLE), DIMENSION(45,45), INTENT(OUT) :: V 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
