      MODULE upcase_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  08:36:11  03/09/06  
      SUBROUTINE upcase (KEYWRD, N) 
      CHARACTER (LEN = *), INTENT(INOUT) :: KEYWRD 
      INTEGER, INTENT(IN) :: N 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
