      MODULE update_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:04:16  03/09/06  
      SUBROUTINE update (IPARAM, IELMNT, PARAM, c1) 
      USE vast_kind_param,ONLY: DOUBLE 
      INTEGER, INTENT(IN) :: IPARAM 
      INTEGER, INTENT(IN) :: IELMNT 
      REAL(DOUBLE), INTENT(IN) :: PARAM, c1
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
