      MODULE update_I   
      INTERFACE
      SUBROUTINE update (IPARAM, IELMNT, PARAM, c1) 
      INTEGER, INTENT(IN) :: IPARAM 
      INTEGER, INTENT(IN) :: IELMNT 
      DOUBLE PRECISION, INTENT(IN) :: PARAM, c1
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
