      MODULE vecprt_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:05:04  03/09/06  
      SUBROUTINE vecprt (A, NUMM) 
      USE vast_kind_param,ONLY: DOUBLE 
      REAL(DOUBLE), DIMENSION(*), INTENT(INOUT) :: A 
      INTEGER, INTENT(IN) :: NUMM 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
