      MODULE volume_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  17:49:42  03/20/06  
      REAL(KIND(0.0D0)) FUNCTION volume (VECS, NDIM) 
      USE vast_kind_param,ONLY: DOUBLE
      INTEGER, INTENT(IN) :: NDIM  
      REAL(DOUBLE), DIMENSION(3,NDIM), INTENT(IN) :: VECS       
      END FUNCTION  
      END INTERFACE 
      END MODULE 
