      MODULE volume_I   
      INTERFACE
      DOUBLE PRECISION FUNCTION volume (VECS, NDIM) 
      INTEGER, INTENT(IN) :: NDIM  
      DOUBLE PRECISION, DIMENSION(3,NDIM), INTENT(IN) :: VECS       
      END FUNCTION  
      END INTERFACE 
      END MODULE 
