      MODULE w2mat_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  12:41:19  03/10/06  
      SUBROUTINE w2mat (WW, W, LMW, LIMIJ, LIMKL) 
      USE vast_kind_param,ONLY: DOUBLE 
      integer, INTENT(INOUT) :: LMW 
      integer, INTENT(IN) :: LIMIJ 
      integer, INTENT(IN) :: LIMKL 
      real(DOUBLE), DIMENSION(LIMKL,LIMIJ), INTENT(IN) :: WW 
      real(DOUBLE), DIMENSION(LMW,LMW), INTENT(OUT) :: W       
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
