      MODULE worder_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  10:47:18  03/09/06  
      SUBROUTINE worder (CC, LM7, IOUT2, W) 
      USE vast_kind_param,ONLY: DOUBLE 
      real(DOUBLE), DIMENSION(*), INTENT(INOUT) :: CC 
      integer, INTENT(IN) :: LM7 
      integer, INTENT(IN) :: IOUT2 
      real(DOUBLE), DIMENSION(*), INTENT(IN) :: W 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
