      MODULE writmo_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:05:05  03/09/06  
      SUBROUTINE writmo 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
