      MODULE wrttxt_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:04:17  03/09/06  
      SUBROUTINE wrttxt (IPRT) 
      INTEGER, INTENT(IN) :: IPRT 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
