      MODULE wstore_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  12:41:19  03/10/06  
      subroutine wstore (w, kr, ni, ilim)
      integer, intent (in) :: ilim
      double precision, dimension (ilim, ilim), intent (out) :: w
      integer, intent (inout) :: kr
      integer, intent (in) :: ni
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
