      MODULE xerbla_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  22:48:56  03/08/06  
      SUBROUTINE xerbla (SRNAME, INFO) 
      character (LEN = 6), INTENT(IN) :: SRNAME 
      integer, INTENT(IN) :: INFO 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
