      MODULE xxx_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  11:04:17  03/09/06  
      SUBROUTINE xxx (TYPE, I, J, K, L, R) 
      CHARACTER (LEN = 1), INTENT(IN) :: TYPE 
      INTEGER, INTENT(IN) :: I 
      INTEGER, INTENT(IN) :: J 
      INTEGER, INTENT(IN) :: K 
      INTEGER, INTENT(IN) :: L 
      CHARACTER (LEN = *), INTENT(OUT) :: R 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
