set(CPACK_ARCHIVE_COMPONENT_INSTALL ON)

if("${CPACK_GENERATOR}" MATCHES "TGZ|ZIP")
   set(CPACK_COMPONENT_INCLUDE_TOPLEVEL_DIRECTORY ON)
   set(CPACK_COMPONENTS_ALL_IN_ONE_PACKAGE ON)
   set(CPACK_COMPONENTS_ALL main redist)
endif()
