name: CI

on:
  push:
    branches:    
      - main
      - mdi-portability-test
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

jobs:
  linux-local:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check number of cores
        run: |
          lscpu
          lscpu | grep "CPU(s):                       " | awk '{print $2}' > num_cores
          echo "NUM_CORES=$(cat num_cores)" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: '3.11'
          channels: conda-forge
      - name: Conda info
        shell: bash -el {0}
        run: conda info
      - name: Conda list
        shell: pwsh
        run: conda list

      - name: Install dependencies with conda-forge
        run: |
          conda activate test
          conda install numpy
          conda install openblas

      - name: Configure MOPAC with CMake
        run: |
          conda activate test
          cmake -B build \
            -DMDI=ON
#            -DPython3_EXECUTABLE=$CONDA/bin/python

      - name: Build MOPAC with Make
        run: |
          conda activate test
          cmake --build build -- -j$NUM_CORES

  linux-remote:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check number of cores
        run: |
          lscpu
          lscpu | grep "CPU(s):                       " | awk '{print $2}' > num_cores
          echo "NUM_CORES=$(cat num_cores)" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: '3.11'
          channels: conda-forge
      - name: Conda info
        shell: bash -el {0}
        run: conda info
      - name: Conda list
        shell: pwsh
        run: conda list

      - name: Install dependencies with conda-forge
        run: |
          conda activate test
          conda install numpy
          conda install openblas
          conda install mdi

      - name: Configure MOPAC with CMake
        run: |
          conda activate test
          cmake -B build \
            -DMDI=ON
#            -DPython3_EXECUTABLE=$CONDA/bin/python

      - name: Build MOPAC with Make
        run: |
          conda activate test
          cmake --build build -- -j$NUM_CORES